### ISSUE TITLE
Backup

### ISSUE THREAD

**Issue by Galiwyx** [akhilrex/podgrab#1]
Hi,
Awesome work ! I'm searching podcast grabber for months ! Thank you very much.

I have a problem, Downloads folder is empty, no error on logs : 

```root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='podgrab' --net='bridge' -e TZ="Europe/Paris" -e HOST_OS="Unraid" -e 'CHECK_FREQUENCY'='30' -p '6680:8080/tcp' -v '/mnt/user/appdata/podgrab/':'/config':'rw' -v '/mnt/user/Downloads/':'/data':'rw' 'akhilrex/podgrab' ```

```
2020/11/07 14:24:28 [32m/api/db/dbfunctions.go:30
[0m[33m[0.789ms] [34;1m[rows:10][0m SELECT * FROM `podcast_items` ORDER BY pub_date desc LIMIT 10
[GIN] 2020/11/07 - 14:24:28 | 200 | 1.999848ms | 192.168.1.4 | GET "/episodes"
[GIN] 2020/11/07 - 14:24:28 | 304 | 56.274µs | 192.168.1.4 | GET "/webassets/axios.min.js"
[GIN] 2020/11/07 - 14:24:28 | 304 | 46.794µs | 192.168.1.4 | GET "/webassets/vue.js"
[GIN] 2020/11/07 - 14:24:28 | 304 | 74.153µs | 192.168.1.4 | GET "/webassets/vue-toasted.min.js"
[GIN] 2020/11/07 - 14:24:32 | 200 | 391.268µs | 192.168.1.4 | GET "/podcastitems/e18a8d66-b300-4a15-8e20-af22b77871cd/download"
/assets/Les Grosses Ttes/Emission-du-5-novembre-2020.mp3
```

Nothing is found on Downloads folder.

Thank you again :)

**Comment by akhilrex** [comment]
Hi 

The mount path in the container for data is /assets. You are using /data. Try changing that and let me know if that works.

PS: I realize that I had wrongly entered it as /data in the docker-compose file which is probably why you got it wrong. I have fixed it as well.

**Comment by Galiwyx** [comment]
Perfect thank you !
