### ISSUE TITLE
No Player Page

### ISSUE THREAD

**Issue by stevenmccurdy** [akhilrex/podgrab#100]
I feel like I'm missing something but I can't figure out where the player page. My instance doesn't have a menu item for the player. I Used the docker-compose example in the readme on an Unraid system.

**Comment by akhilrex** [comment]
Are you not getting any of the highlighted options?

![image](https://user-images.githubusercontent.com/576190/117380427-4902af80-aef7-11eb-90bb-d023095ebfeb.png)

**Comment by stevenmccurdy** [comment]
I'm not. I'm also not getting dark mode. Am I on an old release maybe? I even tried pulling the docker image with the latest tag.
![Screenshot_20210506_201001_com brave browser](https://user-images.githubusercontent.com/31633581/117388182-7cb5e900-aea7-11eb-972e-ddaf16f1e077.jpg)

**Comment by akhilrex** [comment]
Dark mode can be enabled on the settings page.

Can you try this on any other device? Check if you see any console errors.

Thanks and Regards

Akhil Gupta

**Comment by stevenmccurdy** [comment]
Hi, thanks for your help. Dark mode wasn't in settings, I think I was actually on a previous version. I did a docker-compose down -v and then removed the orphan image and then brought it back up. I now have player and dark mode.

For whatever reason the image wasn't being updated (I had pulled an old image quite a while ago) but the fault lies on me and my system. Sorry to take up your time!

**Comment by akhilrex** [comment]
I recommend that you use something like watchtower which will keep your
containers updated.

Thanks and Regards

Akhil Gupta
