### ISSUE TITLE
Generate RSS Feeds

### ISSUE THREAD

**Issue by kucksdorfs** [akhilrex/podgrab#109]
I would like to cache my podcasts locally, but then allow serving of the files to a podcast app on my phone. If the files aren't downloaded to the Podgrab server, then do a 301/302 redirect to the original URL.

**Comment by kucksdorfs** [comment]
Correction, the HTTP Status codes should be 307/308 per the Wikipedia article stating the 302 has been superseded by 303 and 307.

**Comment by florianbeisel** [comment]
I second this, it would be cool if there was a way to point my local podcasts to a RSS feed generated by podgrab. It would be fine for me if it only showed currently available episodes on the podgrab instance. I wouldn't be needing the HTTP redirect

**Comment by akhilrex** [comment]
Already in development

Thanks and Regards

Akhil Gupta

**Comment by akhilrex** [comment]
This has been done. Please rebuild the container after this build is complete. You will be able to get RSS feeds for tags as well as a common feed for all episodes (settings page)

**Comment by Vctrsnts** [comment]
> I would like to cache my podcasts locally, but then allow serving of the files to a podcast app on my phone. If the files aren't downloaded to the Podgrab server, then do a 301/302 redirect to the original URL.

Hello.

How solved this problem? Because have a locally podcast but podgrab not show this podcast.

Thanks
