### ISSUE TITLE
Thanks and Github Sponsorship

### ISSUE THREAD

**Issue by mjtechguy** [akhilrex/podgrab#11]
Akhil, thanks so much for writing this. This is a great product and it really solves an issue for me.

Do you have any plan to setup Github sponsorship? I dont really trust putting my info into the "Buy Me A Coffee" link.

Thanks!

**Comment by akhilrex** [comment]
Hi Mike

I am happy that you find Podgrab useful. I have already applied for the GitHub sponsorship and am currently on the waitlist (for quite some time). I Will update you whenever it goes live.

Please feel free to create bug reports and feature requests.

**Comment by mjtechguy** [comment]
Thanks @akhilrex. I will watch for the Github sponsorship and will definitely contribute once it is live.

Have an amazing day!

**Comment by mjtechguy** [comment]
Just sent some support via "Buy Me A Coffee". Thanks!

![image](https://user-images.githubusercontent.com/29070994/106181905-292b5500-616c-11eb-9fa6-b510df2d4ffa.png)

**Comment by akhilrex** [comment]
That's very kind of you. Thanks
