### ISSUE TITLE
I can't pull docker image

### ISSUE THREAD

**Issue by s-kaczmarek** [akhilrex/podgrab#111]
**Please complete the following information**
 - Installation Type: Docker
 - Have you tried using the latest docker image / code base: I think so - I used docker compose file provided in read my of your project

**Describe the bug**

```
docker_admin@docker_test:~$ docker pull akhilrex/podgrab
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: x509: certificate has expired or is not yet valid
```

**To Reproduce**

`$ docker pull akhilrex/podgrab`

**Expected behavior**

I expected to build the container from your image with docker compose file.

**Comment by akhilrex** [comment]
That seems like a docker issue. Try again maybe in sometime or try using
the GitHub image repository.

Thanks and Regards

Akhil Gupta

**Comment by s-kaczmarek** [comment]
Yes, you were right! That was just a temporary docker issue. Everything works just fine now, thank you for that sweet software! :smiley:
