### ISSUE TITLE
Save playback position

### ISSUE THREAD

**Issue by Tuphal** [akhilrex/podgrab#116]
*Before creating a bug report please make sure you are using the latest docker image / code base.*

**Please complete the following information**
 - Installation Type: Docker
 - Have you tried using the latest docker image / code base yes, v2021.06.20
 
**Describe the bug**
Save the last position of the file.

**Expected behavior**
Continue play, where I (accidentally) stopped.

**Comment by akhilrex** [comment]
This functionality is already there. It saves your player position and resumes when you play the same file again. This data, though, is stored only in the browser and does not work cross devices. 

To verify, play any podcast in the episodes list and let it play for some time. Then close the player and click play on the same podcast on the episodes page. It should resume from near the point you last left.

I am closing this issue for now. Please reopen if this does not work.
