### ISSUE TITLE
[Feature Request] Config option for backups

### ISSUE THREAD

**Issue by ouifi** [akhilrex/podgrab#117]
Can there be an option added to disable the automated backups? It doesnt work on the docker container (for me anyways, but I will investigate that and report it separately). I also have my own system of backing up the data and dont need additional hard drive space wasted to the auto-generated backups.

**Comment by akhilrex** [comment]
Adding this config option would be an added unnecessary complexity. Moreover, the backup only backs up the database file which will never be more than a few kbs. 

I have fixed the breaking backup links as you had reported. Please rebuild the container once this build is complete.

**Comment by ouifi** [comment]
Ah! Thanks so much for fixing this so quickly. I didn't realize that the backups were for the config and db only. I guess that's fine, as it'll be much less data than the audio files.
