### ISSUE TITLE
RSS Feeds from Tags and Settings Possibly Not Compliant

### ISSUE THREAD

**Issue by NOForker** [akhilrex/podgrab#121]
I'm trying to add the RSS feeds from tags, trying the one from Settings as well, to Pocket Casts. It tells me that it is "Unable to find a podcast at this URL" when attempting to add it. I viewed the feed in an RSS reader that can play enclosures, but enclosures don't appear in these feeds. Is there any information I can share for further testing/troubleshooting?

**Comment by akhilrex** [comment]
Open the feed URL in a browser and copy paste the content here.

Thanks and Regards

Akhil Gupta

**Comment by NOForker** [comment]
Akhil,

I appreciate the help, but is there a way that I can send you the browser content and not make it public here? I'd rather not have my server information public. 

Thanks,
Neil

**Comment by akhilrex** [comment]
My GitHub username is also my Gmail username.

Thanks and Regards

Akhil Gupta

**Comment by NOForker** [comment]
Akhil,

I think the problem may be that the "type" param is missing from the enclosure element in the RSS feeds. If I attempt to play an episode within one of the Podgrab RSS feeds in the Apple Podcasts app on my Mac, it downloads the episode file to my Downloads folder without a file extension. If I add ".mp3" to the file, then it will play it. Reviewing the emails I sent to you, it looks like Podgrab generates an enclosure type as `type=""`, but the podcast apps are looking for something more like `type="audio/mpeg"`.

Hope that helps!

Regards,
Neil

**Comment by akhilrex** [comment]
Hi

I have made some changes to the RSS feed including the type change you mentioned. Please rebuild the container once the current build is finished and let me know it it help.

**Comment by NOForker** [comment]
Akhil,

It appears to be working better. I am able to get Pocket Casts to play episodes as long as they are downloaded. Apple Podcasts plays the files as well now.

When I added the podcast to Pocket Casts, it offered some feedback on the feed, so this is just general feedback, and may be useful for features to add later…

> ### No artwork found
> Solution: Tag a JPG or PNG image using one of the following tags and a valid link address:
> `<image><url>http://www.example.com/podcast.jpg</url></image>`
> or
> `<itunes:image href="http://www.example.com/podcast.jpg" />`
> ### Your podcast doesn't seem to have an author
> Solution: Get some credit for your work by adding the following tag to your feed: `<itunes:author>Author’s Name Goes Here</itunes:author>`

Regards,
Neil

**Comment by akhilrex** [comment]
Sounds good. Will look into it.

Thanks and Regards

Akhil Gupta

**Comment by muse-sisay** [comment]
> My GitHub username is also my Gmail username. Thanks and Regards Akhil Gupta

Is there a discord server for Podgrab?

**Comment by akhilrex** [comment]
Not yet.

Thanks and Regards

Akhil Gupta
