### ISSUE TITLE
[Feature Request] Pausing feeds

### ISSUE THREAD

**Issue by shooftie** [akhilrex/podgrab#124]
Sometimes I have feeds that I want to keep around but I do not want to actively download e.g. regular news feeds.

Having the ability to keep them in the list to download from on an ad-hoc basis would be really useful.

**Comment by akhilrex** [comment]
Hi

This is done. Please rebuild the container with the latest image.

**Comment by shooftie** [comment]
Good man. Looks good. Works well.
