### ISSUE TITLE
[Feature request] Link to original feed somewhere in the UI

### ISSUE THREAD

**Issue by shooftie** [akhilrex/podgrab#126]
I realised that the original feed URL is completely hidden once the feed is added to the list.

Some link somewhere that allows you to visit the original feed would be helpful as this might help to diagnose issues e.g. dead feeds

**Comment by akhilrex** [comment]
This has been done. Please rebuild the container with the latest image.

**Comment by shooftie** [comment]
You machine! You are knocking these down as quickly as I can set them up.
