### ISSUE TITLE
Android App

### ISSUE THREAD

**Issue by redairforce** [akhilrex/podgrab#127]
Can someone build a simple Android App that would allow offline download? 
An alternative would be to create an OPML export that creates a separate RSS feed that links back to your server URL. This way, you could still use your server as your own private collection, but use something like Podcast Addict. I've added my podgrab/rss to things like Podcast Addict, but it piles all the shows together as one single show.

**Comment by akhilrex** [comment]
You can create tags and tag multiple podcasts together on whatever basis
you want. Tags get their own RSS feed which contains episodes of only
specific podcasts. See if that might help.

Thanks and Regards

Akhil Gupta

**Comment by akhilrex** [comment]
Did this help?
