### ISSUE TITLE
[Feature Request] - Support Premium, Paid, Podcast Subscription Authentication

### ISSUE THREAD

**Issue by FlexGunship** [akhilrex/podgrab#128]
Currently there are no Docker-deployable Podcast aggregators which support paid subscriptions (like Podcast Addict or MediaMonkey do).

An example RSS feed which requires authentication is https://mysteriousuniverse.org/feed/muplushq/

Request a feature add to support this capability.

**Comment by akhilrex** [comment]
Try adding the podcast RSS in the following format.

***@***.***/


This should work.

Thanks and Regards

Akhil Gupta

**Comment by FlexGunship** [comment]
Thanks for the reply -- are the stars meant to be the username and password for the paid account?

**Comment by FlexGunship** [comment]
Here's an example from MediaMonkey:

![image](https://user-images.githubusercontent.com/86869314/127729970-7115b12b-a1b7-42e1-9a09-990b75d25fbb.png)

**Comment by akhilrex** [comment]
Oh. I had replied to your ticket using email and github converted content to starts


USERNAME:PASSWORD@mysteriousuniverse.org/feed/muplushq

**Comment by FlexGunship** [comment]
Oh, got it -- tried with and without the "https://" but still no luck here:

![image](https://user-images.githubusercontent.com/86869314/127730129-87b74861-32e2-43a9-aa2b-dcb239cda1b1.png)

**Comment by akhilrex** [comment]
add https at beginning anf remove from after the @

https://USERNAME:PASSWORD@mysteriousuniverse.org/feed/muplushq

**Comment by FlexGunship** [comment]
Dude! Legendary!! It worked. 

Like, uh, 10 minutes after I spun up a dedicated Windows VM just to solve this. But I'm totally satisfied and impressed. Recommend adding a note or documenting this feature somehow.

Maybe it's ultra-standard in podcast RSS world, but I couldn't find this info anywhere.

**Comment by akhilrex** [comment]
I am happy that it worked out for you. 

You can buy me beers here https://www.buymeacoffee.com/akhilrex

**Comment by akhilrex** [comment]
I am happy that it's working for you.

Thanks and Regards

Akhil Gupta
