### ISSUE TITLE
[Feature Request] Full Fledged Podcast Player?

### ISSUE THREAD

**Issue by tomershvueli** [akhilrex/podgrab#13]
Thanks for your hard work on this, @akhilrex !

I'm wondering if you have plans to make this project a potential go-to for podcast listening? A few major things I see that could help get there: 
- Being able to play the podcast via the PodGrab web interface
- List entire show notes, not simply the description
- Turn this into a PWA to make it mobile friendly

**Comment by akhilrex** [comment]
This is exactly the plan. Since podgrab has been received so well I plan to
make a lot more features into it. A proper API and player are the next big
changes to come.


Thanks and Regards

Akhil Gupta

**Comment by tomershvueli** [comment]
@akhilrex that's great to hear! I look forward to keeping an eye on progress and chipping in where I can.

**Comment by Code-Slave** [comment]
if you go down that rabbit hole look at implementing the subsonic api server side so clients can talk to the server. especially mobile. Id be much more into using my existing clients to play podcasts

look at navidrome. its a server in go but no podcast support. if you make this a server like that you will grow in users incredibly

**Comment by akhilrex** [comment]
> if you go down that rabbit hole look at implementing the subsonic api server side so clients can talk to the server. especially mobile. Id be much more into using my existing clients to play podcasts
> 
> look at navidrome. its a server in go but no podcast support. if you make this a server like that you will grow in users incredibly

@Code-Slave I have started looking into it. Wrote some code so that Clementine now recognizes Podgrab as a subsonic server but unfortunately it doesn't have podcast support to it is not showing podcast listing. Can you recommend any Sobsonic client that has podcast support that I can use to test. Windows client preferably

**Comment by akhilrex** [comment]
> Thanks for your hard work on this, @akhilrex !
> 
> I'm wondering if you have plans to make this project a potential go-to for podcast listening? A few major things I see that could help get there:
> 
> * Being able to play the podcast via the PodGrab web interface
> * List entire show notes, not simply the description
> * Turn this into a PWA to make it mobile friendly

Hi @tomershvueli 

I have added a player to the podgrab platform. Pull the latest image and check it out.

**Comment by tomershvueli** [comment]
@akhilrex wow, this looks great! (Also first time seeing the dark mode which is clutch!) My moonshot wish list for this now would be to be able to 'queue' up podcast episodes a la Spotify. So add specific episodes to the player (as opposed to automatically add all downloaded episodes), remove some if needed, reorder, etc. The speed that this was shipped is quite impressive though!

**Comment by akhilrex** [comment]
I am happy that you like this. I am trying to figure out queuing already.
Hope to release it soon.

Thanks and Regards

Akhil Gupta

**Comment by akhilrex** [comment]
> @akhilrex wow, this looks great! (Also first time seeing the dark mode which is clutch!) My moonshot wish list for this now would be to be able to 'queue' up podcast episodes a la Spotify. So add specific episodes to the player (as opposed to automatically add all downloaded episodes), remove some if needed, reorder, etc. The speed that this was shipped is quite impressive though!

@tomershvueli Not sure if you noticed but you have the ability to play specific episodes/podcasts even now. The only thing missing is adding episodes to the queue.

**Comment by tomershvueli** [comment]
@akhilrex definitely saw that, very cool!
