### ISSUE TITLE
[Feature request] Ability to choose pagination size

### ISSUE THREAD

**Issue by shooftie** [akhilrex/podgrab#130]
Something like...

![image](https://user-images.githubusercontent.com/2161844/127765999-88ae3ea1-595c-4465-9de2-92e2af58c45e.png)

**Comment by akhilrex** [comment]
Done. Please rebuild container with the latest image.

**Comment by shooftie** [comment]
I have this on the unified episode list (`/episodes`). Thank you.

It is missing from the feed page, however (`/podcasts/.../view`).
