### ISSUE TITLE
Radio Streaming

### ISSUE THREAD

**Issue by uGeek** [akhilrex/podgrab#131]
What do you think, taking advantage of the streaming player, have a section to listen to your favorite radio stations? Could be imported using a .m3u8 file

Great job. Congratulations
Thanks

**Comment by akhilrex** [comment]
Hi

Podgrab is primarily a podcast downloader/archiver with the player just for 'completeness'. I don't plan to invest time in enhancing the player.

I recommend that you use podgrab in conjunction with a better standalone player where podgrab can act as a backend for the player. The new RSS features (complete as well as tag specific) will make it much more easier for you as well.
