### ISSUE TITLE
Audio volume is silently reset between episodes

### ISSUE THREAD

**Issue by komic** [akhilrex/podgrab#133]
I'm using the latest version of Firefox and PodGrab. After lowering the volume during an episode, the next one in my playlist will start playing to the default level despite the volume bar not moving.

**Comment by akhilrex** [comment]
Hi @komic 

I have fixed this. Please rebuild your container with the latest image when it is built and this should work for you.

**Comment by komic** [comment]
Thanks, I'm not seeing this anymore!
