### ISSUE TITLE
Unable to add podcast

### ISSUE THREAD

**Issue by SolveSoul** [akhilrex/podgrab#135]
*Before creating a bug report please make sure you are using the latest docker image / code base.*

**Please complete the following information**
 - Installation Type: Docker
 - Have you tried using the latest docker image / code base: yes

**Describe the bug**
I'm running podgrab on my Synology via Docker and whenever I try to add a podcast it briefly shows a blue loading bar after disappearing and nothing was added in the end. 

**To Reproduce**
1. Go to "Add podcast"
2. Add podcast from iTunes (or RSS "https://fokuzrecordings.com/feed/podcast", with the same result): I tried "Fokuz Recordings"
3. Click "add"

**Expected behavior**
Expected behavior is the podcast being added. Or as an added bonus, a visualisation of the error in the webapp.

**Additional context**
The logs:
```
[GIN] 2021/08/24 - 07:42:58 | 200 | 11.201172282s |      172.18.0.1 | GET      "/ws"
[GIN] 2021/08/24 - 07:42:58 | 200 |    1.548474ms |      172.18.0.1 | GET      "/add"
https://itunes.apple.com/search?term=fokuz+recordings&entity=podcast
Response status: 200 OK
[GIN] 2021/08/24 - 07:43:05 | 200 |  306.342859ms |      172.18.0.1 | GET      "/search?q=fokuz%20recordings&searchSource=itunes"

2021/08/24 07:43:15 /api/db/dbfunctions.go:17 record not found
[0.247ms] [rows:0] SELECT * FROM `podcasts` WHERE `podcasts`.`url` = "https://fokuzrecordings.com/feed/podcast" ORDER BY `podcasts`.`id` LIMIT 1
https://fokuzrecordings.com/feed/podcast
Response status: 200 OK
[GIN] 2021/08/24 - 07:43:15 | 500 |  219.380146ms |      172.18.0.1 | POST     "/podcasts"


2021/08/24 07:43:15 [Recovery] 2021/08/24 - 07:43:15 panic recovered:
runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:212 (0x453132)
/usr/local/go/src/runtime/signal_unix.go:720 (0x452fb2)
/api/service/podcastService.go:188 (0x90600a)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.2/context.go:165 (0xa6ec9a)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.2/recovery.go:99 (0xa84628)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.2/context.go:165 (0xa6ec9a)
/api/main.go:215 (0xaad41a)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.2/context.go:165 (0xa6ec9a)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.2/recovery.go:99 (0xa84628)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.2/context.go:165 (0xa6ec9a)
```

Docker image used: `akhilrex/podgrab                    latest    cd90f2c772c6   10 days ago    32.4MB`

**Comment by akhilrex** [comment]
Please rebuild the container with the latest image and try again. I have fixed this.
