### ISSUE TITLE
Deleting podcast and files from the WebUI leaves title folder and album art on file system

### ISSUE THREAD

**Issue by austozi** [akhilrex/podgrab#138]
**Please complete the following information**
 - Installation Type: Docker
 -  Have you tried using the latest docker image / code base: yes (Version: 2021.08.25)

**Describe the bug**
Deleting an entire podcast and its files deletes leaves the album art (folder.jpg) in the title folder on the file system.

**To Reproduce**
1. Go to PodGrab home page and subscribe to a podcast feed. Download a few episodes and verify the audio files and album art are present on the file system.
2. On the PodGrab home page, delete the entire title by clicking the trash bin icon and selecting "Delete files and podcast" and wait for the confirmation: "Podcast deleted successfully".
3. Return to the file system to check on the files. The audio files have been deleted, but the title folder and album art remain.

**Expected behavior**
The entire title folder associated with the deleted title (including the album art) should be deleted from the file system.

**Comment by akhilrex** [comment]
I have fixed this. Please rebuild your container once the build process is complete.
