### ISSUE TITLE
[Feature Request] File Naming based on metadata (or just Julian date)

### ISSUE THREAD

**Issue by adammckay** [akhilrex/podgrab#14]
When I listen to podcasts, it is easiest to keep them in folders for each podcast.  You have done this and it works well.  Now, it would be nice if the filenames started with the Julian date (2021-01-14-PodcastName.mp3) so that they naturally sorted themselves.  Currently, you are using just the name and they all just get jumbled out of chronological order.
I suppose you could get sophisticated and add a metadata mask like many other downloaders do, but for me, `<podcast name>/<julian date>-<episode name>.<file extension>` is good enough.  The mask might be popular because others would probably prefer all podcasts in one folder as: `<podcast name>-<julian date>-<episode name>.<file extension>`.

Examples:
multi-folder
My Podcast/2021-01-01-Happy New Year.mp3
or
single folder
My Podcast-2021-01-01-Happy New Year.mp3

**Comment by akhilrex** [comment]
Hi. I have released a fix for that. Please rebuild the container with the latest image and on the settings page enable the "Append episode date to episode file name" (I have set it as false by default). This will come into effect for all future downloads. You can delete and re add podcasts if you want this to happen to all files.
