### ISSUE TITLE
[Feature Request] only store latest episode with prefixed filename

### ISSUE THREAD

**Issue by 000MDK** [akhilrex/podgrab#143]
option to set a podcast to only download and store the latest episode with a prefixed filename e.g. latest.mp4 - useful for automatic program schedules of newest episodes in disquetv/ersatztv, shortcutting and news video podcasts in general

**Comment by 000MDK** [comment]
I'm leaving this all for consideration only.
possible solutions to the problem
- with cron:
#/bin/sh
LATEST=$(ls -1tr "/path/to/Podcast/Title" | tail -1)
cp "/path/to/podcast/title"/"$LATEST" \
   /path/to/outputfolder/latest.mp4
problem: does not watch a folder, can be solved with inotifywait etc though
- with filebot, inotifywait
problem: bigger footprint, dependcies etc
--> best solution would be doing it directly in podgrab, but it's a niche feature, I totally get it.

**Comment by muse-sisay** [comment]
> From what I understood, you would like to only keep the latest episode of a  show.

@000MDK  Here is my take on the problem. I am opting for `incron` package instead. Using incron, the script will be notified of file creation (IN_CREATE) in your Podgrab assets directory. It will then remove previous episode file and create a symbolic link 
in your output path ( I assume this is. where disquetv/ersatztv will look for `latest` episodes.)

**I am assuming you are using linux.**

1. Start by installing the package
```console
sudo apt install incron
sudo yum install incron
```

2.  Allow your user account to run `incrontab -e` commands
```console
sudo echo $USER >> /etc/incron.allow
```

3.  Save this in `/usr/bin/local/podgrab-notifier`.  Change the value of `O_PATH` to your output path( path monitored by disquetv/ersatztv)
```bash 
#!/bin/bash
# File podgrab-notfier
# ver 0.1  by Muse Sisay

SHOW_PATH=$1
FILE=$2
FILE_EXT=${FILE##*.}

SHOW_NAME=$(basename "$SHOW_PATH")

O_PATH="changethis"  # edit this
LATEST_SHOW_PATH="$O_PATH/$SHOW_NAME"

# Delete last episode
previous_link=$(find "$LATEST_SHOW_PATH" -name "latest*" -exec basename {} +)

if [[ -n $previous_link  ]] ; then
	LAST_FILE=$(readlink  "$LATEST_SHOW_PATH/$previous_link")
	unlink "$LATEST_SHOW_PATH/$previous_link"
	rm -r "$LAST_FILE"

fi

# Create show directory 
if [[ ! -d "$LATEST_SHOW_PATH" ]] ; then 
	mkdir "$LATEST_SHOW_PATH"
fi
	
# Create symbolic link
ln -s "$SHOW_PATH/$FILE" "$LATEST_SHOW_PATH/latest.$FILE_EXT"

```

4.  Run `incrontab -e` and add the following
```console
/path/to/podgrab/assests 	IN_CREATE	podgrab-notifier $@ $#
```
 
You are good to go. :) 
Muse Sisay

**Comment by 000MDK** [comment]
👍 Very nice :) - Your solution is a complete guide, it could be added as is to the wiki of this project.🥇

**Comment by muse-sisay** [comment]
I am glad you found it helpful,( I was afraid you might not be able to see it because it was a closed issue). Let me know if you find weird issues with the script.

Unfortunately Podgrab doesn't have a wiki yet.

**Comment by 000MDK** [comment]
problem: incron does not support folders with spaces at the current state - solution: `ln -s`

Also, how about something like `O_PATH=$3` and `podgrab-notifier $@ $# changethis` ?
FYI, you still get notifications like normal, even if issue is closed.

**Comment by muse-sisay** [comment]
It is not a problem, there is a bug in the current version of incron. [Github Issue](https://github.com/ar-/incron/issues/55). Try installing version `0.5.10`

```console
sudo apt remove incron
wget "http://archive.ubuntu.com/ubuntu/pool/universe/i/incron/incron_0.5.10-3build1_amd64.deb"
sudo dpkg -i incron_0.5.10-3build1_amd64.deb
```
Does it work?? 

<br>

> Also, how about something like `O_PATH=$3` and `podgrab-notifier $@ $# changethis` ?

Woah, you're right. No need to mess with the script. Just change O_PATH to `O_PATH=$1`.

```console
/path/to/podgrab/assests 	IN_CREATE	podgrab-notifier "/path/to/disquetv/ersatztv" $@ $# 
```
```bash
#!/bin/bash
# File podgrab-notfier
# ver 0.1  by Muse Sisay

SHOW_PATH=$2
FILE=$3
FILE_EXT=${FILE##*.}

SHOW_NAME=$(basename "$SHOW_PATH")

O_PATH=$1
LATEST_SHOW_PATH="$O_PATH/$SHOW_NAME"
```

Thanks for the tip

**Comment by 000MDK** [comment]
I prefer just using the latest incron and `ln -s` to a substitute directory without spaces instead, but you have to use `ln -L` in the script or the link won't show up on samba shares.
so far the script worked when I ran it manually and I have a working link, just edited $3, the ln option for a hardlink, customized the paths a bit and localized the filename, incron.service is up and running and I will post back what happens when a new episode is added. Looking very promising :)
PS: you're welcome, got to thank you for pointing me to incron.. apes together strong? ;)

**Comment by 000MDK** [comment]
I don't really need the rm and because of double-linking it wasn't working anyway (rm: not possible to remove '' file not found)
```
if [[ -n $previous_link  ]] ; then
	unlink "$LATEST_SHOW_PATH/$previous_link"

fi
```
this way it works :) 👍

**Comment by muse-sisay** [comment]
May it is because you have your top directory as a hard link. Even if you delete the original file, the hard link is still pointing to the same inode. You will still have the file.

> ```
> if [[ -n $previous_link  ]] ; then
> 	unlink "$LATEST_SHOW_PATH/$previous_link"
> 
> fi
> ```

You will still have the episode file in podgrab assets folder. `unlink` only removes the symbolic link.


My friend you just went and made the entire thing really complicated, by creating a hard link to your top directory. 

I have never heard of "apes together strong". Is it a saying?

**Comment by 000MDK** [comment]
so in your first post, I guess you need to change `/usr/bin/local` to `/usr/local/bin`
My top directory is a symlink to the working directory, from there i hardlink the file - of course, `LAST_FILE=$(readlink  "$LATEST_SHOW_PATH/$previous_link")` does not work in that situation, so the subsequent `rm` command fails.
I could use `previous_file=$SHOW_PATH/$(ls -t "$SHOW_PATH"| head -2 | tail -1 )` and `rm $previous_file` though.
PS: It's meme from a movie that was used recently for community collaboration, you sure looked it up, but I edited it because was also very thoughtless to say without context when all I really meant to say was "happy to work with you, shake your hand" 🙂

**Comment by muse-sisay** [comment]
Yeah you are right. It should be `/usr/local/bin`. I will edit my first post accordingly.

I have lost you on the symbolic stuff. I am trying to go back, read previous replies and understand how you have set it up the script. Maybe you can explain to me who you set it up, what your assets folder is, and your samba share.

Yeah, I asked my friend what it was. He didn't believe that I haven't watched it yet. I will be watching it next week. (which one should I start with) It nice working with you too!!

**Comment by 000MDK** [comment]
`"/srv/data/Music/Podcast/Showtitle with Spaces"` -> symlink -> `/srv/data/tmp/Podcast/Showtitlenospaces` //workaround for incrond bug
incrond is watching `/srv/data/tmp/Podcast/Showtitlenospaces` with the script
`/srv/data/tmp/Podcast/Showtitlenospaces/Showtitle-date.mp4`-> hardlink -> `/srv/data/Video/Podcast/Showtitlenospaces/latest.mp4` //done by script on execution
smb-shares:
/srv/data/Video
/srv/data/Music
ErsatzTV has three libraries setup:
/srv/data/Video/Movies
/srv/data/Video/TV-Shows
/srv/data/Video/Podcast
podgrab is downloading to:
/srv/data/Music/Podcast

I'd start in chronological order with Dawn of Planet of the Apes, I guess

**Comment by muse-sisay** [comment]
Hi 000MDK,

I did a little bit of experimenting to find out what was causing the script not to work on your setup. So ,I found out that `incron(incrontab 0.5.12)` doesn't send notification when the path that it is watching is a symbolic link. 

I tried to replicate your setup,  this is the experiment I did
<details>
    <summary>Experiment </summary>

### Setup
I first created a folder `test-folder`. And then created a symbolic link to that folder called `test-folder-link`. This experiment is to test out if incron works with symbolic linked folders. And not folders with spaces.

```console
$ mkdir test-folder
$ ln -s test-folder test-folder-link
```
then  I added entry to incron, to watch the normal folder and symbolic link folder

```console
/path/to/test-folder	        IN_CREATE	  echo "Created $#" >  /dev/pts/0 
/path/to/test-folder-link	IN_CREATE	  echo "Created $# (link)" >  /dev/pts/0 
```
replace the `/dev/pts/0`. with the output you get from `tty` command.
If a file is created inside `test-folder` incron will print ` "Created FILE_NAME"` to my terminal. If file is created inside `test-folder-link`  incron will print  `"Created FILE_NAME (link)"` to my terminal.

### Test
So I went ahead and created files inside the folders. 
```console
$ touch test-folder/file1
$ touch test-folder-link/file1
```

### Result 
incron detected file creation inside test-folder and outputted the message to my terminal. But it did not do so when I created a file inside test-folder-link. My conclusion is incron doesn't watch for file creation inside symbolic link folders.

</details>

i.e 
- There is a bug in `incrontab 0.5.12` that doesn't allow you to have spaces in the folder you are watching.
- incron (at-least incrontab 0.5.12) doesn't like it when you give it a symbolic folder to watch.  It will ignore the directory.


I am glad that the script is working for you, although you have changed most of it : ).  If I had to set this up I would use incron 0.5.10. Thanks I will start with Dawn of Planet of the Apes.

_I am writing all this in the hopes it helps someone out._

**Comment by 000MDK** [comment]
Hmm, interesting on an up-to-date Debian10 (Linux KRZ0NAS 5.10.0-0.bpo.7-amd64 #1 SMP Debian 5.10.40-1~bpo10+1 (2021-06-04) x86_64 GNU/Linux), incron Version: 0.5.12-1+deb10u1 
 i did my testing with following results:

> command:
> ```
> startdir=/srv/DATA/tmp/dir
> slinkdir=/srv/DATA/tmp/slink
> tempdir=/srv/DATA/tmp
> touch $startdir/test1.file
> ln -s $slinkdir $startdir
> touch $tempdir/test
> chmod 755 $tempdir/test
> ```
> 
> command:
> ```
> nano $tempdir/test
> ```
> edit/add:
> ```
> #/bin/sh
> echo test action for $1/$2 in $3 >> /srv/DATA/tmp/log 
> ```
> 
> command:
> `incrontab -e`
> edit/add:
> ```
> /srv/DATA/tmp/dir    IN_CREATE       /srv/DATA/tmp/test $@ $# "dir"
> /srv/DATA/tmp/hlink    IN_CREATE       /srv/DATA/tmp/test $@ $# "hlink"
> /srv/DATA/tmp/slink    IN_CREATE       /srv/DATA/tmp/test $@ $# "slink"
> ```
> 
> command:
> ```
> touch $startdir/test2.file
> touch $slinkdir/test4.file
> ```
> 
> command:
> `service incron status`
> output:
> ```
> Sep 13 03:29:14 redacted incrond[12676]: PATH (/srv/DATA/tmp/dir) FILE (test2.file) EVENT (IN_CREATE)
> Sep 13 03:29:14 redacted incrond[12676]: (root) CMD (      /srv/DATA/tmp/test /srv/DATA/tmp/dir test2.file "dir")
> Sep 13 03:29:28 redacted incrond[12676]: PATH (/srv/DATA/tmp/dir) FILE (test4.file) EVENT (IN_CREATE)
> Sep 13 03:29:28 redacted incrond[12676]: (root) CMD (      /srv/DATA/tmp/test /srv/DATA/tmp/dir test4.file "dir")
> ```
> 
> command:
> `cat /srv/dev-disk-by-label-DATA/tmp/log`
> output:
> ```
> test action for /srv/DATA/tmp/dir/test2.file in dir
> test action for /srv/DATA/tmp/dir/test4.file in dir
> ```

Have fun, but don't expect too much of it ;)

**Comment by muse-sisay** [comment]
Did you mean to do `ln -s $startdir $slinkdir` instead of `ln -s $slinkdir $startdir` ?

Nice test btw, so much better than mine. So I went ahead and followed your test.

My Test : 

```bash
tempdir=/home/pi/TRASH/tmp
startdir=$tempdir/dir
slinkdir=$tempdir/slinkdir
```

- Next
```console
mkdir $stardir                            # create folder
ln -s $startdir $slinkdir                 # create symbolic link
```

- I added these entries to `incron`. Pasted your logger script and saved it as logger.sh
```text
/home/pi/TRASH/tmp/dir  IN_CREATE       /home/pi/TRASH/tmp/logger.sh $@ $# "dir"
/home/pi/TRASH/tmp/slinkdir     IN_CREATE       /home/pi/TRASH/tmp/logger.sh $@ $# "slink"
```
```bash
#!/bin/bash
# File : logger.sh
echo "Hello"
echo "test action for $1/$2 in $3" >> /home/pi/TRASH/tmp/log
```

- I went ahead and created file in `$stardir` and `$slinkdir`
```console
touch dir/test2.file
touch slinkdir/test3.file
```

- and and ... nothing in `/home/pi/TRASH/tmp/log`. Maybe error with file permission. so I checked the system logs
```bash
$ journalctl -u incron.service
...
incrond[408]: PATH (/home/pi/TRASH/tmp/dir) FILE (test2.file) EVENT (IN_CREATE)
incrond[408]: (pi) CMD (/home/pi/TRASH/tmp/logger.sh /home/pi/TRASH/tmp/dir test2.file "dir")
incrond[408]: PATH (/home/pi/TRASH/tmp/dir) FILE (test3.file) EVENT (IN_CREATE)
incrond[408]: (pi) CMD (/home/pi/TRASH/tmp/logger.sh /home/pi/TRASH/tmp/dir test3.file "dir")
```` 
and voilá there they are. But wait I created the test3.file inside $slinkdir. But incron is calling the task for $startdir. Maybe because it is the first one??

just to check I went ahead and removed the first line of my incron entry and making it look like this
```test
/home/pi/TRASH/tmp/slinkdir	IN_CREATE	/home/pi/TRASH/tmp/logger.sh $@ $# "slink"
```
and created test7.file
```
incrond[408]: PATH (/home/pi/TRASH/tmp/slinkdir) FILE (test7.file) EVENT (IN_CREATE)
incrond[408]: (pi) CMD (/home/pi/TRASH/tmp/logger.sh /home/pi/TRASH/tmp/slinkdir test7.file "slink")
```

_it works_ hmmm interesting. Okay what happens if I interchange the two tasks

 ```
/home/pi/TRASH/tmp/slinkdir	IN_CREATE	/home/pi/TRASH/tmp/logger.sh $@ $# "slink"
/home/pi/TRASH/tmp/dir	IN_CREATE	      /home/pi/TRASH/tmp/logger.sh $@ $# "dir"
```

```console
touch dir/test20.file
touch slinkdir/test21.file
```
the logs show 
```
incrond[408]: PATH (/home/pi/TRASH/tmp/slinkdir) FILE (test20.file) EVENT (IN_CREATE)
incrond[408]: (pi) CMD (/home/pi/TRASH/tmp/logger.sh /home/pi/TRASH/tmp/slinkdir test20.file "slink")
incrond[408]: PATH (/home/pi/TRASH/tmp/slinkdir) FILE (test21.file) EVENT (IN_CREATE)
incrond[408]: (pi) CMD (/home/pi/TRASH/tmp/logger.sh /home/pi/TRASH/tmp/slinkdir test21.file "slink")
```

_hmm hmm_ `:put your conclusions here:`

---
- [My conclusions](https://github.com/akhilrex/podgrab/issues/143#issuecomment-917438474) were wrong.  It matter's how you order your incron tasks. And it should work with symbolic linked folder too.
- I realized you cannot create hard link for a folder  :-).
 
Is this script working for you? Can you share it?

**Comment by akhilrex** [comment]
> option to set a podcast to only download and store the latest episode with a prefixed filename e.g. latest.mp4 - useful for automatic program schedules of newest episodes in disquetv/ersatztv, shortcutting and news video podcasts in general

Sorry for being late with this thread.

This is really a very specific request which does not really go with the main motivation of Podgrab so I do not plan to build it. Although I am happy that you have found a solution here.

**Comment by 000MDK** [comment]
> This is really a very specific request which does not really go with the main motivation of Podgrab so I do not plan to build it. Although I am happy that you have found a solution here.

Understanding and living opensource, I made this feature request not as a demand, as I'm lucky enough having podgrab as it is. So I provided a quick and dirty solution with it, as this might be the right place and also am very happy of the outcome already. 😁 Just a big, big thank you for this project! 👍 

Still think doing this in podgrab itself is cleaner though, so I just leave the following here:
I guess, this just needs a little change in `service/fileService` for
`import (
...
"os/exec"
)`
and in `func Download`
`prg := "ln -h"
ext := filepath.Ext(parsed)
arg1 := folder + "/latest" + ext
cmd := exec.Command(prg, finalPath, arg1)
stdout, err := cmd.Output()`
(and maybe a toggle in the options for this.)

**Comment by 000MDK** [comment]
> Did you mean to do `ln -s $startdir $slinkdir` instead of `ln -s $slinkdir $startdir` ?

Yes, the following should clear things up a little:
```
root@redacted:/srv/DATA/tmp# ls
dir  log  test
root@redacted:/srv/DATA/tmp# cd dir
root@redacted:/srv/DATA/tmp/dir# ls
root@redacted:/srv/DATA/tmp/dir# cd ..
root@redacted:/srv/DATA/tmp# ln -s $slinkdir $startdir
root@redacted:/srv/DATA/tmp# ls ./dir
slink
root@KRZ0NAS:/srv/dev-disk-by-label-DATA/tmp# cat /srv/dev-disk-by-label-DATA/tmp/log
test action for /srv/dev-disk-by-label-DATA/tmp/dir/slink in dir
root@redacted:/srv/DATA/tmp# ln -s $startdir $slinkdir
root@redacted:/srv/DATA/tmp# ls
dir  log  slink  test
```
> Is this script working for you? Can you share it?

Everthing working smooth like a charm, daily news videocast getting scheduled in ErsatzTV.
As you see, I didn't change much and supplied everthing I changed already, except the untested alternative route for getting the previous_file thingy done 😅


```
#!/bin/bash
# File podgrab-notfier
# ver 0.1  by Muse Sisay
# edits by MDK, maybe 0.1.5

SHOW_PATH=$2
FILE=$3
FILE_EXT=${FILE##*.}
#DATASTORE=$4
SHOW_NAME=$(basename "$SHOW_PATH")

O_PATH=$1
LATEST_SHOW_PATH="$O_PATH/$SHOW_NAME"

# Delete last episode
previous_link=$(find "$LATEST_SHOW_PATH" -name "aktuell*" -exec basename {} +)
previous_file=$SHOW_PATH/$(ls -t "$SHOW_PATH"| head -2 | tail -1 )
#previous_file=$(cat $DATASTORE)
if [[ -n $previous_link  ]] ; then
        unlink "$LATEST_SHOW_PATH/$previous_link"
        rm $previous_file
fi

# Create show directory
if [[ ! -d "$LATEST_SHOW_PATH" ]] ; then
        mkdir "$LATEST_SHOW_PATH"
fi

#Store file location
#echo $SHOW_PATH/$FILE > $DATASTORE

# Create symbolic link
ln -L "$SHOW_PATH/$FILE" "$LATEST_SHOW_PATH/aktuell.$FILE_EXT"


```

BTW Hardlinks for dirs are not the best idea as you can make loop out of the fs-tree, that's why -d -F options won't get you far nowadays, even if they still exist - bind mounts are a way to create another inode for a dir on modern systems though, and that's pretty much the same. Was about to include that in the test, but there was really no reason to.
`mount --bind olddir newdir` but beware: `rm newdir` really works and doesn't just delete the link.
