### ISSUE TITLE
Feature request: allow skipping ahead and backwards

### ISSUE THREAD

**Issue by poblabs** [akhilrex/podgrab#146]
It would be awesome if the player had an option to skip X seconds ahead and backward. Maybe configurable in options - like 30 seconds forward and 10 seconds backwards. This way we can skip commercials easier, or rewind back in case we missed something.

**Comment by akhilrex** [comment]
I am using a third party library for building the player which does not support this "out of the box". I could theoretically build it but that's not something that aligns with the vision of the tool. The player was built just for the same of "completeness"

I recommend that you use Podgrab as the downloading and archiving tool and use it as the backend for a better dedicated Podcast player.
