### ISSUE TITLE
[Feature Request] Download indicator

### ISSUE THREAD

**Issue by anselstetter** [akhilrex/podgrab#15]
First of all thank you for your work.
I really like the minimalistic design.

It would be great to have a progress bar, when downloading podcasts.
Currently you have to refresh the page to check if the file has been downloaded.

I didn't have a look at the code, so I don't know how feasible it would be to implement this feature.

**Comment by akhilrex** [comment]
I have updated the episode counter on the podcast listing page to display all the episodes that are downloaded as well as in the process of downloading. This should give you a better sense of download progress.

I will be building a better UI with the UI overhaul sprint which is the next thing to start.
