### ISSUE TITLE
Thumbnails of large images.

### ISSUE THREAD

**Issue by jtagcat** [akhilrex/podgrab#151]
Serving hundreds of images with 4k episode/podcast covers is bandwidth-intensive — slow and costly.

The same goes for local cache, storage space and iops usage.

Scale the images down to a more reasonable size (say 150-200px squares?). Compression is usually also done on the fly by the web server (does gin?), though while at it, lossless compression wouldn't hurt.

**Comment by akhilrex** [comment]
I have added lazyloading of images on the webui which will only load the images when they are in the view. I think that should resolve your problem. 

Building image compression does not really align with the vision and purpose of the tool which is primarily to act as a downloader and archiver.
