### ISSUE TITLE
[Feature Request] RSS Per Podcast

### ISSUE THREAD

**Issue by Kussie** [akhilrex/podgrab#155]
Currently you can export an RSS feed of all items, or by tags.  It would be nice to have an RSS feed per Podcast as well.  At the moment i am using Tags for this purpose with the name of the Podcast and import that into my apps on mobile, the only downside to this approach is it doesn't then include all the art and description of the original podcast.

**Comment by akhilrex** [comment]
Why do you require podgrab generated feed for that? You can use the original feed from the podcast to do that. 

You can find the podcast feed url by clicking the _i_ button on the podcast page and copying the URL field.

**Comment by muse-sisay** [comment]
> Why do you require podgrab generated feed for that? 

I think what Kussie means is he wants to consume the content he download using his phone. He might be in an area where he doesn't have internet connection or because he has the files already downloaded on his machine, why download them again. The only way to do it right now, as far as I know, is to tag the podcast then export the tag RSS or export the entire RSS feed. Which  both methods solve Kussie's needs. But there is room for improvement. Creating tag for individual podcast seems a hacky way of doing this, atleast for me. I would like to see the ability to create tag per show on Podgrab.

The other downside I also noticed while exporting RSS feed with Podgrab and then using it with AntennaPod is podcast images never load.

I like the idea of grouping podcasts into tag. When exporting it would be really cool to have a collage (4x4) of all the cover arts of the shows as the cover art for that group.

( _an after thought:_ this is beyond the scope of Podgrab and needs help from AntennaPod devs. What if, instead of exporting each individual show's RSS feed it was possible to just put the IP address or FQDN of the machine running Podgrab into AntennaPod and AntennaPod will let you choose the podcasts you want to sync on your device. This is just a thought) 

I know we are asking too much of you. I think it's time we buy you a beer.

**Comment by akhilrex** [comment]
> I think what Kussie means is he wants to consume the content he download using his phone. 

This makes sense. This use case entirely slipped my mind.

@Kussie I have done this and pushed the code. Wait for the new image to get built and rebuild your container. You will be able to find the link in the "i" button for podcasts in the home page. Bottom link.

@muse-sisay I am not sure why AntennaPod is not picking up images since I am sending image URLs in the feed.

**Comment by muse-sisay** [comment]
> @muse-sisay I am not sure why AntennaPod is not picking up images since I am sending image URLs in the feed.

I have no idea to be honest. I have been having problem with Podgrab loading album arts, see #81 . I suspect the problem is my Firefox browser since no-one has raised this issue. As for AntennaPod not picking p

I have bought you a beer. Unfortunately though I pressed "support" with out writing you a message. Thank you for this awesome project, feature request and bug fixes.

**Comment by akhilrex** [comment]
Is there any specific podcast for which I can test this issue?

**Comment by mmguero** [comment]
The per-podcast RSS feeds works great. I think I have the same issue as @muse-sisay. I can import the per-podcast feeds into AntennaPod fine, but here's what the subscriptions screen looks like:

![Screenshot_20211101-131139](https://user-images.githubusercontent.com/13872653/139727933-9f5b9067-9cf5-4101-9b10-7727809caa40.png)

Not a dealbreaker as I can still read the descriptions, though.

**Comment by muse-sisay** [comment]
> Is there any specific podcast for which I can test this issue?

Any podcast will work, non of them will show podcast poster in AntennaPod.

> @muse-sisay I am not sure why AntennaPod is not picking up images since I am sending image URLs in the feed.

I compared the original RSS feed and the feed generated by PodGrab. The original RSS feed seems to have `itunes:` before each tag or key value.  For example 

*original RSS feed*
```
<itunes:author>Jack Rhysider</itunes:author>
<itunes:image href="https://megaphone.imgix.net/podcasts/df1a01b8-8214-11eb-a059-d7ed58ae9ff2/image/The-Spy-Square.jpg?ixlib=rails-2.1.2&max-w=3000&max-h=3000&fit=crop&auto=format,compress"/>
```
*feed generated by PodGrab*
```
<author/>
<image href="http://192.168.1.10:8086/podcastitems/14af365f-d267-41c6-a1b1-c2374f3175c4/image">The Spy</image>
```

As the iTunes tag is the only difference between the two feed I am assuming that is why AntennaPod is not picking up the images.

**Comment by digitlength** [comment]
I'd like to leave a 'me too' in here!

I have a similar use-case - I'd like to download the episode from the wider internet once, then share with LAN-only devices via PodGrab's RSS feed. But I've had limited success when trying with Android apps:

- PocketCast - refuses to load the _Podgrab Feed_ RSS link
- Escapepod - refuses to load _Podgrab Feed_ RSS link, saying that it contains no valid episodes
- Antenna Pod - seems more forgiving of the RSS feed, but is missing the images.

If it helps, here's some comparisons of the Podgrab RSS vs. the original author's RSS, in this case the Friday Night Comedy Podcast from BBC Radio 4:

**Podcast info**

**BBC Radio 4**
```
<title>Friday Night Comedy from BBC Radio 4</title>
<link>http://www.bbc.co.uk/programmes/p02pc9pj</link>
<description>Download the best satirical comedy from Radio 4, every Friday. Features The News Quiz, The Now Show and Dead Ringers.</description>
<itunes:summary>Download the best satirical comedy from Radio 4, every Friday. Features The News Quiz, The Now Show and Dead Ringers.</itunes:summary>
<itunes:author>BBC Radio 4</itunes:author>
<itunes:owner>
	<itunes:name>BBC</itunes:name>
	<itunes:email>RadioMusic.Support@bbc.co.uk</itunes:email>
</itunes:owner>
<itunes:new-feed-url>https://podcasts.files.bbci.co.uk/p02pc9pj.rss</itunes:new-feed-url>
<language>en</language>
<ppg:seriesDetails frequency="weekly" daysLive="14"/>
<ppg:systemRef systemId="pid.brand" key="p02pc9pj"/>
<ppg:systemRef systemId="pid.genre" key="C00195"/>
<ppg:network id="radio4" name="BBC Radio 4"/>
<image>
	<url>http://ichef.bbci.co.uk/images/ic/3000x3000/p07kfvzb.jpg</url>
	<title>Friday Night Comedy from BBC Radio 4</title>
	<link>http://www.bbc.co.uk/programmes/p02pc9pj</link>
</image>
<itunes:image href="http://ichef.bbci.co.uk/images/ic/3000x3000/p07kfvzb.jpg"/>
<copyright>(C) BBC 2021</copyright>
<pubDate>Fri, 05 Nov 2021 19:01:00 +0000</pubDate>
<itunes:category text="Comedy"/>
<itunes:explicit>no</itunes:explicit>
<media:rating scheme="urn:simple">nonadult</media:rating>
<atom:link href="http://www.bbc.co.uk/programmes/p02pc9pj/episodes/downloads.rss" rel="self" type="application/rss+xml"/>
```

**Podgrab**
Interestingly serving _blank.png_ within the _image_ tag. But even then, the URL is served quite differently to how the BBC does it (via a <url> within <image>, and also via an <itunes:image href="..."/>)
```
<language></language>
<link>http://192.168.1.176:8080/allTags</link>
<title>Friday Night Comedy from BBC Radio 4</title>
<description>Download the best satirical comedy from Radio 4, every Friday. Features The News Quiz, The Now Show and Dead Ringers.</description>
<type></type>
<summary>Download the best satirical comedy from Radio 4, every Friday. Features The News Quiz, The Now Show and Dead Ringers.</summary>
<image href="http://192.168.1.176:8080/webassets/blank.png">Friday Night Comedy from BBC Radio 4</image>
```

**Episode info**
**BBC Radio 4**
```
<item>
	<title>The Now Show - 5th November ft Glenn Moore, Daliso Chaponda and Stiff &amp; Kitsch</title>
	<description>Steve Punt and Hugh Dennis present the week via topical stand-up and sketches from the BBC Radio Theatre in front of a remote audience.

Joining them from a safe distance is Glenn Moore talking about returning back to the office, Daliso Chaponda on the future of the Metaverse and Stiff &amp; Kitsch with a song about all the things we can now worry about again now the pandemic is over (kind of).

Voice Actors: Luke Kempner and Katie Norris

Producer: Pete Strauss
Production Co-Ordinator: Sarah Sharpe

BBC Studios Production</description>
	<itunes:subtitle>Steve Punt and Hugh Dennis present the week via topical stand-up and sketches</itunes:subtitle>
	<itunes:summary>Steve Punt and Hugh Dennis present the week via topical stand-up and sketches from the BBC Radio Theatre in front of a remote audience.

Joining them from a safe distance is Glenn Moore talking about returning back to the office, Daliso Chaponda on the future of the Metaverse and Stiff &amp; Kitsch with a song about all the things we can now worry about again now the pandemic is over (kind of).

Voice Actors: Luke Kempner and Katie Norris

Producer: Pete Strauss
Production Co-Ordinator: Sarah Sharpe

BBC Studios Production</itunes:summary>
	<pubDate>Fri, 05 Nov 2021 19:01:00 +0000</pubDate>
	<itunes:duration>1674</itunes:duration>
	<enclosure url="http://open.live.bbc.co.uk/mediaselector/6/redir/version/2.0/mediaset/audio-nondrm-download/proto/http/vpid/p0b2gh8w.mp3" length="26784000" type="audio/mpeg"/>
	<ppg:enclosureLegacy url="http://open.live.bbc.co.uk/mediaselector/6/redir/version/2.0/mediaset/audio-nondrm-download/proto/http/vpid/p0b2gh8w.mp3" length="26784000" type="audio/mpeg"/>
	<ppg:enclosureSecure url="https://open.live.bbc.co.uk/mediaselector/6/redir/version/2.0/mediaset/audio-nondrm-download/proto/https/vpid/p0b2gh8w.mp3" length="26784000" type="audio/mpeg"/>
	<guid isPermaLink="false">urn:bbc:podcast:p0b2gldx</guid>
	<link>http://www.bbc.co.uk/programmes/p0b2gldx</link>
	<itunes:explicit>clean</itunes:explicit>
	<media:content url="http://open.live.bbc.co.uk/mediaselector/6/redir/version/2.0/mediaset/audio-nondrm-download/proto/http/vpid/p0b2gh8w.mp3" fileSize="26784000" type="audio/mpeg" medium="audio" expression="full" duration="1674"/>
	<itunes:author>BBC Radio 4</itunes:author>
	<ppg:canonical>/programmes/p0b2gldx</ppg:canonical>
</item>
```

**Podgrab**
```
<item>The Now Show - 5th November ft Glenn Moore, Daliso Chaponda and Stiff &amp; Kitsch
	<title>The Now Show - 5th November ft Glenn Moore, Daliso Chaponda and Stiff &amp; Kitsch</title>
	<description>Steve Punt and Hugh Dennis present the week via topical stand-up and sketches from the BBC Radio Theatre in front of a remote audience.&#xA;&#xA;Joining them from a safe distance is Glenn Moore talking about returning back to the office, Daliso Chaponda on the future of the Metaverse and Stiff &amp; Kitsch with a song about all the things we can now worry about again now the pandemic is over (kind of).&#xA;&#xA;Voice Actors: Luke Kempner and Katie Norris&#xA;&#xA;Producer: Pete Strauss&#xA;Production Co-Ordinator: Sarah Sharpe&#xA;&#xA;BBC Studios Production</description>
	<encoded></encoded>
	<summary>Steve Punt and Hugh Dennis present the week via topical stand-up and sketches from the BBC Radio Theatre in front of a remote audience.&#xA;&#xA;Joining them from a safe distance is Glenn Moore talking about returning back to the office, Daliso Chaponda on the future of the Metaverse and Stiff &amp; Kitsch with a song about all the things we can now worry about again now the pandemic is over (kind of).&#xA;&#xA;Voice Actors: Luke Kempner and Katie Norris&#xA;&#xA;Producer: Pete Strauss&#xA;Production Co-Ordinator: Sarah Sharpe&#xA;&#xA;BBC Studios Production</summary>
	<episodeType></episodeType>
	<author></author>
	<image href="http://192.168.1.176:8080/podcastitems/a10f7044-5c3f-469a-a438-b0aa60fc6633/image">The Now Show - 5th November ft Glenn Moore, Daliso Chaponda and Stiff &amp; Kitsch</image>
	<guid isPermaLink="false">a10f7044-5c3f-469a-a438-b0aa60fc6633</guid>
	<clipId></clipId>
	<pubDate>Fri, 05 Nov 2021 19:01:00 +0000</pubDate>
	<duration>1674</duration>
	<enclosure url="http://192.168.1.176:8080/podcastitems/a10f7044-5c3f-469a-a438-b0aa60fc6633/file" length="26874805" type="audio/mpeg"></enclosure>
	<link>http://192.168.1.176:8080/allTags</link>
	<episode></episode>
</item>
```

Not sure if this is of any use - hope it helps!

**Comment by akhilrex** [comment]
@digitlength  @muse-sisay @mmguero Can you please try again after rebuilding containers with latest images. You might have to re-add the podcasts to AntennaPod.

**Comment by muse-sisay** [comment]
👍🏾 Images load. Everything is working as expected.

**Comment by digitlength** [comment]
Can confirm also - images are now showing. Only had to click the refresh icon within the Subscriptions window on AntennaPod, did not need to reimport RSS feeds!

**Comment by mmguero** [comment]
Sorry, I haven't been around for a few weeks. Works great for me now, too.
