### ISSUE TITLE
No logout button/Lack of multi-user environment

### ISSUE THREAD

**Issue by ebiscaia** [akhilrex/podgrab#160]
**Please complete the following information**
 - Installation Type: Docker
 - Have you tried using the latest docker image / code base: yes
 
**Describe the bug**
It is not a bug but two feature requests
   - A log off option
   - Possibility to create more users

Thanks

**Comment by akhilrex** [comment]
Hi

Podgrab is primarily an internal archiving tool that does not necessarily need support for multiple users. I do not intend to build it anytime in the future.

A simple workaround could be to have a separate instance of Podgrab for other user which can be put behind basic auth that Podgrab already supports.
