### ISSUE TITLE
Podcasts longer than one hour doesn't show proper progress

### ISSUE THREAD

**Issue by ScuttleSE** [akhilrex/podgrab#161]
*Before creating a bug report please make sure you are using the latest docker image / code base.*

**Please complete the following information**
 - Installation Type: Docker
 - Have you tried using the latest docker image / code base yes

**Describe the bug**
Podcasts longer than one hour wraps around and show progress as 00:01 after one hour

**To Reproduce**
1. Download podcast that is longer than one hour
2. Play it
3. Observe what happends after one hour
![screenshot-2021-10-02_11:07:58](https://user-images.githubusercontent.com/4344284/135710239-f4e865f8-3a7e-4a78-979a-a1dd9bd54481.png)
![screenshot-2021-10-02_11:07:36](https://user-images.githubusercontent.com/4344284/135710244-7fa3f8e5-1166-4c94-8bb9-879ce743f93a.png)

**Comment by akhilrex** [comment]
Can you provide me some podcast that has longer episodes for me to test?

**Comment by ScuttleSE** [comment]
https://feeds.twit.tv/twit.xml

That one for example

**Comment by akhilrex** [comment]
Please rebuild the container with the latest image and this will be fixed. 

Thanks @fracai
