### ISSUE TITLE
Settings are saved and applied but reset at a later time

### ISSUE THREAD

**Issue by max0913** [akhilrex/podgrab#163]
*Before creating a bug report please make sure you are using the latest docker image / code base.*

**Please complete the following information**
 - Installation Type: Docker / Current Version | 2021.10.01
 - Have you tried using the latest docker image / code base [yes]

**Describe the bug**
Application settings are saved but later (unknown circumstances) reset. 

**To Reproduce**
1. Go to settings
2. Click to change some settings 
3. Change the value of "How many episodes to be downloaded when a new podcast is added" from 5 to 15
4. See error (one or two days later when you check the settings again)

**Expected behavior**
The settings should not be reset to default after time. 

**Screenshots**

![grafik](https://user-images.githubusercontent.com/4052908/136510998-e0de20d2-c6ea-41e8-8b37-043f9d0f7e7a.png)

**Additional context**
Nothing to add right now

**Comment by akhilrex** [comment]
I am honestly not able to replicate this. Since everything uses the same database are you seeing any other unexpected behavior anywhere else in the app?
