### ISSUE TITLE
Any way to add a podcast but associate episodes to existing files?

### ISSUE THREAD

**Issue by Timmer2021** [akhilrex/podgrab#164]
I have a folder of my favorite podcasts already downloaded.. Is there a way to add a podcast in podgrab and tell that podcast the location of the downloaded files?

**Comment by fracai** [comment]
I did something like this when I started using Podgrab and my solution, unfortunately, was to parse the RSS myself, construct the SQL queries that would create the entries according to the expected Podgrab DB format, and move the files in to place myself. Very hacky and not ideal.

The best, useable, feature that I can think of would be to move the files in to place with the correct names and implement a check where Podgrab checks for the file on disk before downloading. A way to see what the expected path name is would make this easier.

A fuller feature would allow manually matching existing episodes, maybe with some guesses by Podgrab, but that seems like an extensive task.

**Comment by akhilrex** [comment]
I'll be honest. It will be way too much work to make this work since everyone will have their files pre-downloaded files in different formats and file names which would make it difficult to autodetect. 

For most cases it would be easier and faster to download it all again.

**Comment by develroo** [comment]
> I'll be honest. It will be way too much work to make this work since everyone will have their files pre-downloaded files in different formats and file names which would make it difficult to autodetect.
> 
> For most cases it would be easier and faster to download it all again.

Sorry to come to this late. But I have to say, one case where it would be nice to at least acknowledge a podcast already downloaded, is when the sources to that podcast have died. ie. Up on Itunes but the link it points to is dead. One Such podcast is this "Who's Doing What Now - A Doctor Who Podcast" which points to `https://wdwnpod.libsyn.com/rss` which 404's The Podcast stopped in 2022, but as I am migrating from AirsonicAdvance I had already downloaded the entire thing. 

I can probably scrape the metadata still from iTunes as it is cached there, I am even willing to set my own id3 tags if that is necessary.(Assuming there is a schema podgrab is looking for). Even if I do all this, there is no way to get podgrab to read a valid, already downloaded podcast. 

Granted, it is not something that happens every day, but I am mindful how in today's climate data can just vanish from the internet without a trace. So it would be nice to be able to archive podcasts for when they get yanked for whatever reason.

Aside from that, it is a very good podcast app and, aside from not being able to migrate as easily as I would like, does most of what I need it to do. So thanks. 

Just my fourpennethworth.
