### ISSUE TITLE
Downloading multiple episodes in one day

### ISSUE THREAD

**Issue by direkt** [akhilrex/podgrab#17]
I am seeing an issue where if a podcast releases multiple episodes per day, it only downloads the first one released.  Is this a known limitation?  I can provide the name of a podcast where I see the issue with if that helps.

Thanks

**Comment by akhilrex** [comment]
Please share the name / feed URL of the podcast so that I can verify.

Thanks and Regards

Akhil Gupta

**Comment by akhilrex** [comment]
Hi @direkt 

There is no such limitation that's built into the system. I recommend you rebuild the container with the latest image and see if it persists. Please share the podcast name/url with me if it persists. Closing this for now.
