### ISSUE TITLE
"Download all files" does not result in any downloaded files

### ISSUE THREAD

**Issue by shooftie** [akhilrex/podgrab#172]
*Before creating a bug report please make sure you are using the latest docker image / code base.*

**Please complete the following information**
 - Installation Type: Docker
 - Have you tried using the latest docker image / code base: yes – 2021.11.11

**Describe the bug**
"Download all episode files" does not result in any downloaded files, yet "Download to server" on individual files does.

**To Reproduce**
- Add podcast (`Download episodes whenever new podcast is added` is disabled)
- Click "download all episode files" <br><img style="vertical" width="205" alt="Screenshot 2021-11-28 at 09 35 16" src="https://user-images.githubusercontent.com/2161844/143762829-cadbf1c9-e59c-4b03-bcff-6fd066aa54c6.png">
- Episodes summary changes to `(8)/0/8 episodes` suggesting that the episodes **will** download
- Episodes within the podcast lose their "Download to server" button<br><img width="161" alt="Screenshot 2021-11-28 at 09 38 56" src="https://user-images.githubusercontent.com/2161844/143762955-888e3b78-b99b-4332-be70-1e291306ede1.png"><br><img width="161" alt="Screenshot 2021-11-28 at 09 39 25" src="https://user-images.githubusercontent.com/2161844/143762962-f1cfa713-e40a-4c64-a132-d71ffd0d052b.png">
- Files are not downloaded

**Expected behavior**
All files are download as there is nothing else in the queue.

**Screenshots**
https://user-images.githubusercontent.com/2161844/143763079-cba40ad4-d22b-455d-b67b-f00d8d32c566.mov

**Additional context**

**Comment by shooftie** [comment]
This is linked to #110 & #136

Eventually it worked itself out. @akhilrex do you have a bit more clarity on when the download locks are released?

**Comment by WolfgangDpunkt** [comment]
I have the same problem, automatic downloading of new episodes is not working.
 
![grafik](https://user-images.githubusercontent.com/35533844/144265336-294d3535-7298-49e7-bfbf-6467cd77e42c.png)
Version, in Docker Container:  2021.11.11 (on rpi4)
I restarted the container multiple times.

The log says everything is fine:

`
Response status: 200 OK,
http://www.deutschlandfunkkultur.de/podcast-sein-und-streit-das-philosophiemagazin-ganze-sendung.2694.de.podcast.xml,
Processing episodes:  0`

**Comment by shooftie** [comment]
@WolfgangDpunkt can you post your logs? Are you seeing anything like 
```
podgrab    | DownloadMissingEpisodes is locked
```
This was present in my case. Leaving it overnight and it was still there and pretty much as soon as I created this issue it cleared!
```
docker-compose logs | grep locked
```

**Comment by WolfgangDpunkt** [comment]
@shooftie 
Thanks for your reply.
The log excerpt I already posted - that's all it says in principle. Is there somewhere an option to turn on a technically more detailed log, a debug mode?
The keyword `locked` is not to be found.

**Comment by shooftie** [comment]
Not that I know of.

My server is OOA right now but I will give your podcast url a go when I am back up and running to see if I get the same.

**Comment by shooftie** [comment]
Just a thought. Have you tried adding the podcast with different settings e.g. automatically downloading all, automatically downloading fewer, not automatically downloading any and then manually downloading all?

It might help diagnose when @akhilrex or someone cleverer that me eventually makes it here...

**Comment by WolfgangDpunkt** [comment]
Just as a quick feedback, now it apparently works again, for some unknown reason.
I've always had it running as a cron job for an hour every day. Now there are suddenly new podcast episodes again.
Once again thank you for your effort!

**Comment by shooftie** [comment]
@WolfgangDpunkt happy for me to close this?
