### ISSUE TITLE
[Feature Request] option for OPML export to contain Podgrab feed links instead of original URL

### ISSUE THREAD

**Issue by mmguero** [akhilrex/podgrab#173]
It would be convenient to have an option to allow the user to choose whether the `xmlUrl` element in the file generated by the the `OPML export` feature contains the original URL (e.g., `https://feeds.simplecast.com/cYQVc__c`) or the Podgrab feed link (e.g., `https://192.168.0.10/podcasts/46d275b7-c753-4046-a2f3-2388d1d0a27b/rss`).

The original URL is great when migrating the list of podcasts to another tool or app, but the Podgrab feed link would be very useful to allow importing the Podgrab OPML export file into a podcast client so that the one subscription per podcast exists (rather than just the combined feed) while having the subscriptions point to the podgrab server.

**Comment by CHBMB** [comment]
This would be fantastic, and exactly what I was trying to convey when I posted [here](https://github.com/akhilrex/podgrab/issues/155#issuecomment-942675759) previously.

**Comment by akhilrex** [comment]
This feature has been live for some time . You get a dedicated posgrab XML
feed per pocast now.

Thanks and Regards

Akhil Gupta

**Comment by mmguero** [comment]
Right, exactly. And that's great, I am using it, but currently to get those dedicated feeds into my podcast app I have to do some scripting to scrape the per-podcast RSS links and combine them into my own OPML file. What I'm suggesting here is the ability to export an OPML file that contains those dedicated feeds: exactly like the current "export OPML" button in podgrab, only putting the podgrab links in as an option instead of the original feed links. does that make sense?

**Comment by mmguero** [comment]
Or in other words, an option to have `XmlUrl` in [this line](https://github.com/akhilrex/podgrab/blob/master/service/podcastService.go#L151):
```
		toAdd := model.OpmlOutline{
			AttrText: podcast.Summary,
			Type:     "rss",
			XmlUrl:   podcast.URL,
			Title:    podcast.Title,
		}
```

Contain the same URL found [here](https://github.com/akhilrex/podgrab/blob/master/client/index.html#L352):
```
      <tr>
        <td>Podgrab Feed</td>
        <td> <a target="_blank" :href="'/podcasts/'+detailPodcast.ID+'/rss'">Link</a></td>
      </tr>
```

**Comment by akhilrex** [comment]
This is done. Please rebuild the container with the latest image and check the settings page.

**Comment by mmguero** [comment]
Built and tested! Works perfectly, thanks a ton.

**Comment by CHBMB** [comment]
@akhilrex Thank you so much for this, I can't tell you how pleased I am.  Podgrab for me personally is completely and utterly feature complete!

**Comment by akhilrex** [comment]
I am happy that my project is being used :)

Thanks and Regards

Akhil Gupta
