### ISSUE TITLE
dockerhub out of date

### ISSUE THREAD

**Issue by jflattery** [akhilrex/podgrab#176]
*Before creating a bug report please make sure you are using the latest docker image / code base.*

**Please complete the following information**
 - Installation Type: **Docker**
 - Have you tried using the latest docker image / code base **yes**

**Describe the bug**
On two machines (one aarch64 and one x86) I have attempted to download and run the latest image. On both the reported version in the webui is 2021.11.11.

**To Reproduce**
1. docker pull akhilrex/podgrab:latest
2. configure docker-compose.yml
3. docker-compose.yml
4. open web interface and look at version on settings page

**Expected behavior**
Version reported should be 2021.12.03

**Comment by arcoast** [comment]
The latest image was pushed 3 days ago and is versioned 1.0.0 but I've noticed the same as you that the reported version is still `2021.11.11` so I *think* it's a version tagging issue rather than the image being out of date on Docker Hub.

**Comment by arcoast** [comment]
Just looked a bit further into it as I was curious, I think it's been recitfied now with this [commit](https://github.com/akhilrex/podgrab/commit/b9fee7d560fe67a7bc6d4d80a521919402c11ace#diff-9097dbb4df9b32ea2ce946ec90d29c1b00093cd3a02c33b95b1046d7226b872b) and the preceding [commit](https://github.com/akhilrex/podgrab/commit/06671b3d01390b006264ceffc04d8b05d1c19d0f) looking at the history is a feature I'm currently using which was only added in the build from 3 days ago.  Going to hazard a guess the docker image was built between those two commits. :man_shrugging:
