### ISSUE TITLE
[Feature Request] Ability to view current download queue

### ISSUE THREAD

**Issue by spencerhughes** [akhilrex/podgrab#19]
I noticed when I ask an episode to download it says that it's adding to a download queue, but I don't see any way to see the status of that queue in the interface. It would be helpful to know what's being downloaded/how long the queue is.

**Comment by Code-Slave** [comment]
especially on the front page. you list the total. how about line xx/xx
as in 22/44 downloaded

**Comment by akhilrex** [comment]
> especially on the front page. you list the total. how about line xx/xx
> as in 22/44 downloaded

I have done this. Please pull the latest image and it should show you. As for a dedicated page for the queue, I will add it to the pipeline.

**Comment by Code-Slave** [comment]
works perfectly thanks. looking forward to ui work
