### ISSUE TITLE
[Feature Request] Ability to see path for podcast episodes

### ISSUE THREAD

**Issue by spencerhughes** [akhilrex/podgrab#20]
It would be useful to be able to see what file Podgrab thinks it has for the purposes of verifying what it's doing/removing duplicates.

**Comment by akhilrex** [comment]
I can display the path to you but the system currently uses the database to check what all it has downloaded and what all is not downloaded. Duplicate management happens in the DB only.

**Comment by spencerhughes** [comment]
Yeah that works fine - I was more so thinking of removing duplicates from a previous podcatcher/manually downloaded episodes.

**Comment by akhilrex** [comment]
I am still figuring out how that can be done so that people who already have gpodder don't need to download all content again. I'll build this when I figure it out. Closing this issue for now.
