### ISSUE TITLE
Wrong version stated in Settings

### ISSUE THREAD

**Issue by timconsidine** [akhilrex/podgrab#204]
I have pulled the latest docker version
README.MD says `Current Version -2021.12.03`
but Settings page says this at bottom of page 
```
Current Version | 2021.11.11
```
Creates confusion

**Comment by akhilrex** [comment]
Can you please confirm that you have the latest image?

**Comment by jrcastine** [comment]
I just pulled the latest image.

![image](https://user-images.githubusercontent.com/7816656/165076570-f1353f70-9b04-4f5e-8a13-c8329aa74058.png)

**Comment by jflattery** [comment]
Related to #176 which seems to be addressed with newest release

**Comment by jrcastine** [comment]
Confirming this is showing 2022.04.25 with the latest download for arm64 this morning.
