### ISSUE TITLE
simple guide to port changing

### ISSUE THREAD

**Issue by Thomas-O** [akhilrex/podgrab#222]
I have another server on port 8080. Please could you tell me how to install Podgrab (via Docker) so that it uses another port? 

Or perhaps point me to some appropriate general guidance.

Thanks for your help

Thomas

**Comment by muse-sisay** [comment]
Hey @Thomas-O, you just need to change the publish port. In docker you would see something like this `-p 5000:8080`. This means the application inside docker is listening on port 8080 while you localhost/docker is listening on port 5000. Docker internally will redirect the request that arrives on localhost:5000 (or any other IP address that your machine has) to port 8080.

**Comment by Thomas-O** [comment]
> Hey @Thomas-O, you just need to change the publish port. In docker you would see something like this `-p 5000:8080`. This means the application inside docker is listening on port 8080 while you localhost/docker is listening on port 5000. Docker internally will redirect the request that arrives on localhost:5000 (or any other IP address that your machine has) to port 8080.

Thanks for the super-quick advice. 

If I understand correctly, would this be OK?: docker run -d -p **8081**:8080 --name=podgrab

**Comment by muse-sisay** [comment]
Absolutely. Podgrab will be available on port 8081

( Sorry I hit enter before I finished writing a reply )

**Comment by Thomas-O** [comment]
Thanks. I'll give it a whirl and report back. Thanks for helping.

**Comment by Thomas-O** [comment]
It worked. I'd thought about buying another Raspberry Pi to host Podgrab. As a way of saying thank you I'll donate some of the cash I've saved to UNICEF or to the Ukraine fund. Which would you prefer?

**Comment by muse-sisay** [comment]
You would be lucky to get a Raspberry Pi at this time. I have been trying to get CM4 for months now.

If you're planning to donate please consider donating to the people of Tigray. They have been closed off from the outside world for almost 2 years and are very much in need of support.

Thank you very much.
P.s Mark this issue as solved/closed.

**Comment by akhilrex** [comment]
This thread made me happy.
