### ISSUE TITLE
[Feature Request] Spotify Podcast

### ISSUE THREAD

**Issue by Protektor-Desura** [akhilrex/podgrab#232]
Could you think about adding support to auto download podcasts from Spotify?

You could integrate this.

https://github.com/timdorr/spotifeed

This would allow me to download the Joe Rogan podcasts. Thanks.

**Comment by maramazza** [comment]
+1
I think that could be very interesting..

**Comment by billdeys** [comment]
Spotifeed no longer works. Spotify changed the way they host the files and they can't be accesses outside the app any longer.

**Comment by Protektor-Desura** [comment]
Booo oh well it would have been nice. 😂
