### ISSUE TITLE
[Feature Request] Show individual RSS for each show

### ISSUE THREAD

**Issue by ohare93** [akhilrex/podgrab#237]
I want to sync each individual show to my devices via RSS. There is no easy way to find that link, as you can only see the RSS link for a Tag or for all podcasts. But if you export the OPML file, then the individual links are stored in there!

I just want those links to be visible in some easier way :+1:

**Comment by warthurton** [comment]
Hey.  It is there.  

Under your list of podcasts, click on the i - info icon
![image](https://user-images.githubusercontent.com/202251/189903916-b670f04c-97de-4f85-910b-18b441ff1f13.png)

Then you will find the rss under **podgrab feed**

![image](https://user-images.githubusercontent.com/202251/189904100-1023a6c4-9a3f-401c-a302-574dd254fa46.png)

**Comment by ohare93** [comment]
Excellent :clap: glad I just missed it. Thanks for the help

**Comment by warthurton** [comment]
You are welcome. It took me a while to find it as well.
