### ISSUE TITLE
Identical title overwrites existing file

### ISSUE THREAD

**Issue by Unending** [akhilrex/podgrab#25]
When a feed has an episode with the same name podgrab simply overwrites the previous file.

Example feed had 3 years with each 12 episodes named "Drunksmas Day _":
[Half Hour Happy Hour](https://feeds.megaphone.fm/half-hour-happy-hour)

**Comment by akhilrex** [comment]
Hi. I have released a fix for that. Please rebuild the container with the latest image and on the settings page enable the "Append episode date to episode file name" (I have set it as false by default). You might have to delete and readd the podcast after that but then it will not rewrite the file with same name as it will append the release date to the file name.
