### ISSUE TITLE
[Bug] Downloading all episodes of 1 podcast forces download of other podcasts

### ISSUE THREAD

**Issue by undaunt** [akhilrex/podgrab#26]
Hello,

I was re-setting up the app from scratch after adding user: 1000:1000 into my compose. I then did precisely the following steps:

1. Disabled 'download episodes whenever new podcast is added'
2. Imported my OPML file
3. Waited for basic metadata for each podcast to populate
4. Chose only one podcast, and clicked download all.

This kicked off every podcast downloading 5 episodes, the default from 'How many episodes to be downloaded when a new podcast is added' - even though the parent choice of 'Download episodes whenever new podcast is added' was disabled.

I intended to only download all episodes from one specific podcast, but none from anything else. The use case here being I want to archive my favorite shows but have *all* of them contained within the database for future OPML export and/or episode download, but only when I choose.

Thank you.

**Comment by akhilrex** [comment]
Hi 

Can you please tell me was the checkbox for "Automatically download new episodes to the disk" checked or unchecked when you tried this?

**Comment by akhilrex** [comment]
I have fixed this. You will have to destroy to delete the podcasts and re-add them and this should work fine. Thanks for pointing this out.

**Comment by undaunt** [comment]
Hi Akhil,

Yes, the auto download new episodes to disk was checked, however these were not new episodes so to speak. I can confirm this appears to be working. Thanks!
