### ISSUE TITLE
[Feature Request] Basic authentication

### ISSUE THREAD

**Issue by matyasrichter** [akhilrex/podgrab#27]
Thank you for working on this, the project looks amazing - it's great to see modern self-hosted projects like this!

Are you planning on adding some form of basic authentication? I would love to have podgrab exposed to the web, accessible on the go.

**Comment by akhilrex** [comment]
Hi

I have added basic authentication to Podgrab. Just pull the latest image and rebuild the container with a new environment variable `PASSWORD` with its value as whatever you want to use as password. This will enable basic authentication across all routes. Setting it as empty or not setting it would remove auth.

Username is `podgrab`

**Comment by ohare93** [comment]
This does not function properly. I was going crazy trying to work out why it wasn't asking me for my password, here are my findings:

1. Podgrab only asks for the password one time. After that, it is completely open to all. **Even on other browsers or devices.** :skull: 
2. The password is only asked for again upon reset **if the password has been changed** :fearful: 

I don't know if this is something wrong with my setup... Happy to provide any info I can.

When running Podgrab on my Unraid server and exposing it to the internet via reverse proxy, some type of basic auth is needed :sweat_smile:
