### ISSUE TITLE
Github package

### ISSUE THREAD

**Issue by ksurl** [akhilrex/podgrab#28]
I think the new image being built by github actions is still set to private on your github account. The only public one is the old one from october (not docker hub but the packages tab on the profile)

**Comment by akhilrex** [comment]
I'll check this tomorrow.

Thanks and Regards

Akhil Gupta

**Comment by akhilrex** [comment]
Hi

I have set the package visibility to public. Please check and close this issue once you have verified.

**Comment by ksurl** [comment]
working now, thanks.
