### ISSUE TITLE
[Feature Request] Backups in /config instead of /assets

### ISSUE THREAD

**Issue by undaunt** [akhilrex/podgrab#29]
TItle, essentially. Can we either choose the location of our backups, or instead direct them to the config location instead of asset location? I store my assets on a NAS, but keep all of my docker configs, databases, etc. in a separate ZFS location.

Thanks!

**Comment by Code-Slave** [comment]
traditionally this is where its done (config) as most back up their configs nightly

**Comment by akhilrex** [comment]
Yes. I somehow missed this. Have fixed this and pushed the build. Rebuild your container and you should be good to go.
