### ISSUE TITLE
Add Episode Number to Filename

### ISSUE THREAD

**Issue by N7KnightOne** [akhilrex/podgrab#30]
Similar to https://github.com/akhilrex/podgrab/issues/25, could the ability to add an episode number to the file name based off of order of upload?

I found a podcast that did a bulk re-upload of their episodes on the same day and they reuse titles as it is a theatrical reading of a book.

**Comment by akhilrex** [comment]
I have built this and pushed the code. Just pull the latest image and rebuild the container. 

The setting is disabled by default so you will have to enable it on the setting page.

All subsequently downloaded episodes will have episode numbers appended to the file name. Delete and readd any existing podcast in case you want to have this done for all the files.
