### ISSUE TITLE
Missing thumbnail for episode view

### ISSUE THREAD

**Issue by ksurl** [akhilrex/podgrab#43]
I am not sure if it was already happening before the latest update to fix the podcast list thumbnails but in episode tab, Accidental Tech Podcast and Robot or Not do not have thumbnails.

**Comment by akhilrex** [comment]
Will check.

Thanks and Regards

Akhil Gupta

**Comment by akhilrex** [comment]
Checked the RSS feed for both the mentioned podcasts. None of them send image links with the episodes. 

https://feeds.theincomparable.com/robot
https://atp.fm/rss
