### ISSUE TITLE
[Bug] Mismatched Podcasts

### ISSUE THREAD

**Issue by N7KnightOne** [akhilrex/podgrab#44]
Podgrab is downloading the latest podcasts, however, it's not creating update entries in the GUI.

RSS Link of Podcast: https://www.kuow.org/feeds/podcasts/seattlenow/podcasts/rss.xml

Screenshot: ![image](https://user-images.githubusercontent.com/47005674/107088111-4fc33e80-67b1-11eb-9301-71359c2c42f7.png)

ls of the podcast folder: 
`"1-0001-01-01-'Defund'-ideas-police-can-get-behind.mp3"                    1-0001-01-01-Phase-2.mp3                   "1-0001-01-01-Who-will-be-Seattle's-next-mayor.mp3"
 1-0001-01-01-Casual-Friday-with-Chase-Burns-and-Michael-Shawn-Dugar.mp3   1-0001-01-01-The-vaccine-line-jumpers.mp3`

**Comment by akhilrex** [comment]
YET another datetime format to handle!!

I have fixed it and pushed the code. Please rebuild the container with the latest image. Please delete the podcast (everything). You will have to delete all the files from the folder manually. Add the podcast again.
