### ISSUE TITLE
[Feature Request] Multiple Queues/Filters

### ISSUE THREAD

**Issue by undaunt** [akhilrex/podgrab#45]
Related to https://github.com/akhilrex/podgrab/issues/13

Would it be possible to have predefined lists of podcasts in separate queues? IE: I add two politics podcasts (Lets say 538 politics and NPR politics) to one predefined filter, "Political Shows" or whatever. I can then play through that queue, or come back to it later and go to the default recently added queue or another custom queue?

Basically this - https://support.pocketcasts.com/article/episode-filters/

**Comment by akhilrex** [comment]
I have added the concept of tags which will do what you want to achieve. You can tag podcasts with the "Politics" Tag and be able to filter them on the home page or play episodes of specific tags from the Tags page.

Check it out and let me know.

**Comment by undaunt** [comment]
That's pretty awesome! Thanks!

Would it be possible to sort the pre-filtered list in the player by either forward or reverse chronological? Right now it starts at most recent which is not ideal for a serialized story podcast.

Similarly, is it possible to exclude (or give the option to exclude) listened episodes from the playlist?

**Comment by akhilrex** [comment]
I have added all this functionality and released it. You can now do extensive filtering and sorting on the episodes page and then get the player to play that for you. This should take care of almost all the scenarios.

Please pull the latest image and rebuild the container.
