### ISSUE TITLE
Play faster and more...

### ISSUE THREAD

**Issue by uGeek** [akhilrex/podgrab#48]
Great service, I really like it. Congratulations.

I wanted to make three suggestions.

- Play faster. x1.25, x1.5, x1.75 ...
- Play the podcasts added to the list, also in streaming
The hardest,
- Save the playback position, where you stopped listening to the podcast.

So many great thanks

**Comment by akhilrex** [comment]
Done. Rebuild the container with the latest image and check it out.

**Comment by uGeek** [comment]
Many thanks.
