### ISSUE TITLE
[UI Bug] Header Centering & Spacing

### ISSUE THREAD

**Issue by undaunt** [akhilrex/podgrab#49]
There appears to be slightly less white/black space on the `/episodes` page than the other four pages between the page title and the horizontal bars. If you click through all of them you'll notice the difference. 

Also, the home and settings headers appear slightly to the left of where add podcast and player appear. Not sure which pair is truly center and which is off centered.

**Comment by akhilrex** [comment]
Can you please share screenshots? I honestly don't see either of the issues happening on my setup.

**Comment by Code-Slave** [comment]
can confirm. when i click through the menu options there is a notable jump in the episodes header

**Comment by akhilrex** [comment]
Got it. This is fixed the episodes page issue. Please pull the latest image when this build finishes. 

Still not able to see the "slightly to the left" issue. If you could help me see it, I'll be able to fix it.

**Comment by Code-Slave** [comment]
fixed. i cannot confirm the offcenter issue. it looks ok to my old eyes

**Comment by undaunt** [comment]
Screenshot - !(screen)[https://i.imgur.com/XLkcOq2.png]

The browser was only 1-2 px off when I took the shot, but the far right alignment of the lines is more than that.

**Comment by akhilrex** [comment]
CSS wise there is absolutely nothing different across these screens. Closing this for now.
