### ISSUE TITLE
Accented letters removed

### ISSUE THREAD

**Issue by Zazou89** [akhilrex/podgrab#5]
Hey,
Accented letters are deleted from the folder name / file name of the podcast. 
![image](https://user-images.githubusercontent.com/206181/98454781-8fee3300-2168-11eb-93fc-3ad4785b1640.png)
Instead of `Les Grosses Têtes`

**Comment by Zazou89** [comment]
Any news ? 
Thank you =)

**Comment by undaunt** [comment]
Same scenario for a sci-fi podcast I listen to titled "Androids & Aliens", the folder on disk is called "Androids  Aliens".

**Comment by akhilrex** [comment]
I am looking into it.

**Comment by akhilrex** [comment]
I have fixed this. Please pull the latest image and try again. 

Note: The lib I have used to do the filename sanitization flattens the accented characters and replaces them so that they are still readable.

**Comment by Zazou89** [comment]
Thank you, it's working :)
