### ISSUE TITLE
Episode details

### ISSUE THREAD

**Issue by Code-Slave** [akhilrex/podgrab#50]
The episode summary is captured in the db but i dont see any way that will show it. hover, or show summary button in episode list would be nice

**Comment by akhilrex** [comment]
I don't understand what you mean? The summary is being displayed in the episodes list. Check screenshot with highlighting.
![Summary](https://user-images.githubusercontent.com/576190/107166216-4e755a00-69db-11eb-889e-e97167307f85.jpg)

**Comment by Code-Slave** [comment]
Oops. It seems a good number of my podcasts didnt get episode data. (astonishing legends for one) will try a redownload and see whats up

**Comment by akhilrex** [comment]
"astonishing legends" is not setting the standard "summary" field. Changed the code to use description instead. Pull latest image once it is built and rebuild your container. You will have to delete and add the podcast again.

Please close this issue if this solves the issue.

**Comment by Code-Slave** [comment]
Works  now. Thanks
