### ISSUE TITLE
Podcast player on ios mobile

### ISSUE THREAD

**Issue by Code-Slave** [akhilrex/podgrab#51]
Ive tried safari and firefox. When i hit play for an episode it just sits there. nothing happends

**Comment by akhilrex** [comment]
Was it a downloaded episode or one you were streaming directly?

Will check these browsers.

Thanks and Regards

Akhil Gupta

**Comment by Code-Slave** [comment]
Streaming directly

**Comment by akhilrex** [comment]
I tried it on safari on iOS (iPhone 7) and it played fine for both
downloaded and direct streams.

Try waiting for a few seconds and give it time to buffer.

Thanks and Regards

Akhil Gupta

**Comment by Code-Slave** [comment]
shrug. let it sit for 5 minutes and nada. iphone xr

`
[GIN] 2021/02/11 - 01:11:04 | 200 |    1.974047ms |      172.17.0.1 | GET      "/player?&itemId=d46fa439-7d30-4fe1-b725-f0d065777d23"


Player Registered


[GIN] 2021/02/11 - 01:11:04 | 404 |     459.809µs |      172.17.0.1 | GET      "/favicon.ico"


[GIN] 2021/02/11 - 01:11:05 | 206 |    7.671716ms |      172.17.0.1 | GET      "/assets/The NoSleep Podcast/425-2021-02-07-No-Sleep-Podcast-S15E22.mp3"


[GIN] 2021/02/11 - 01:11:05 | 206 |  177.066497ms |      172.17.0.1 | GET      "/assets/The NoSleep Podcast/425-2021-02-07-No-Sleep-Podcast-S15E22.mp3"


[GIN] 2021/02/11 - 01:11:08 | 206 |     226.048µs |      172.17.0.1 | GET      "/assets/The NoSleep Podcast/425-2021-02-07-No-Sleep-Podcast-S15E22.mp3"


[GIN] 2021/02/11 - 01:11:08 | 206 |  264.413853ms |      172.17.0.1 | GET      "/assets/The NoSleep Podcast/425-2021-02-07-No-Sleep-Podcast-S15E22.mp3"


[GIN] 2021/02/11 - 01:11:10 | 206 |  1.512160866s |      172.17.0.1 | GET      "/assets/The NoSleep Podcast/425-2021-02-07-No-Sleep-Podcast-S15E22.mp3"`

**Comment by akhilrex** [comment]
The logs are all fine. No errors. Will try this podcast myself.

Thanks and Regards

Akhil Gupta

**Comment by Code-Slave** [comment]
its not just that. none of them work. will look into this more as much as i can

**Comment by akhilrex** [comment]
Hi

Can you please rebuild the container and check again.

**Comment by Code-Slave** [comment]
works. The only thing is that the placemarker  (the thing that moves during play to show time etc) doesnt move. not a dealbreaker

**Comment by akhilrex** [comment]
Cool. Closing this issue. Will check the placemarker when I get time.
