### ISSUE TITLE
Sow more on episodes screen shows dupe info

### ISSUE THREAD

**Issue by Code-Slave** [akhilrex/podgrab#54]
when you show more it duplicates the episode info example

Born and raised in South America, chilis were the earliest crop domesticated in the continent and among the first items brought back to Europe by Columbus. Today people are really, really into them. Find out all about 'em in this classic episode. Learn more about your ad-choices at https://www.iheartpodcastnetwork.com show less

Born and raised in South America, chilis were the earliest crop domesticated in the continent and among the first items brought back to Europe by Columbus. Today people are really, really into them. Find out all about 'em in this classic episode. Learn more about your ad-choices at https://www.ihea show more

**Comment by akhilrex** [comment]
Fixed in the latest build. rebuild container with the latest image.
