### ISSUE TITLE
Invalid File Format error on OPML import

### ISSUE THREAD

**Issue by tehniemer** [akhilrex/podgrab#55]
I've tried to import both of these files and get an error that says `Invalid File Format`, not sure what's going on. I've renamed them with a `.txt` extension so I could upload, but they were originally `.opml`

[PodcastAddict_OPML_export_20200916_062024.txt](https://github.com/akhilrex/podgrab/files/6019502/PodcastAddict_OPML_export_20200916_062024.txt)
[all-subscriptions.txt](https://github.com/akhilrex/podgrab/files/6019503/all-subscriptions.txt)

**Comment by akhilrex** [comment]
Fixed in the latest build. rebuild container with the latest image.
