### ISSUE TITLE
Episode file names with illegal characters not parsed correctly

### ISSUE THREAD

**Issue by ocai** [akhilrex/podgrab#56]
I have a podcast containing the "|" character in the title. Once the file is saved, the character gets converted into "" instead (U+F027) on a SMB share. As a result, the file cannot be downloaded using the "Download episode file" button since it looks for the file with "|" in it. In addition, the player cannot play the episode either.

I have not tested this with other illegal characters so I don't know if this problem applies to those as well (such as * . " / \ [ ] : ; | ,).

**Comment by akhilrex** [comment]
Please rebuild the container with the latest image and try to delete and redownload the file. Let me know if the issue persists.

**Comment by ocai** [comment]
The file name appears to be fixed now, but I am still having the same issues where I cannot download the file or play the file, even though the file paths match.

Maybe you can try to replicate my issue. The podcast I am having issues in particular with is the "Trash Taste Podcast". The only setting I have checked for changing the file name is "Append episode date to episode file name". The latest episode file is "2021-02-19-How-to-NOT-Flirt-with-a-You-Tuber-Trash-Taste-#37.mp3".

**Comment by akhilrex** [comment]
Try again with the latest image. Delete and redownload. Should work now

**Comment by ocai** [comment]
Thanks! It's working now. I deleted the container and recreated it.
