### ISSUE TITLE
Problems Downloading Episode Files From Web Interface

### ISSUE THREAD

**Issue by coopermf** [akhilrex/podgrab#57]
I am encountering an issue when using the web interface to download an episode already downloaded to my server by the docker container. The podcast player works but when I click the download episode file button it takes me to "https://assests/..." as opposed to the appropriate location to download the file.

**Comment by akhilrex** [comment]
Hi

Please provide the following info

1. On which page are you facing this issue? - All Episodes or A single Podcast listing. (Try downloading it on both and let me know if you face the issue)
2. What is the host platform.
3. Can you see the files on the server?
4. Podcast and Episode name?
5. Are you using a domain with the deployment or an IP?

**Comment by coopermf** [comment]
1. This is across all episodes of different podcasts
2. The host platform is docker on raspberry pi 4
3. Yes, the files are correctly downloaded on to the server
4. Again this is across all podcasts and episodes for me
5. I am using caddy as a reverse proxy but the problem occurs both with the domain and the ip

**Comment by akhilrex** [comment]
Try rebuilding the container with the latest image and try again.

**Comment by coopermf** [comment]
Ok, after rebuilding with the latest image the downloading is working when accessing via the ip. However when I access using the reverse proxy it tries to use my public ip which fails and I have to manually delete the ip and replace it with by domain to successfully download.

**Comment by akhilrex** [comment]
I have tried to fix that as well. Rebuild once more and try again.

Thanks and Regards

Akhil Gupta

**Comment by coopermf** [comment]
Seems to be working with my domain now, thank you so much! This is an awesome project I am loving it so far.
