### ISSUE TITLE
Add support for PodcastIndex.org (as iTunes search alternative)

### ISSUE THREAD

**Issue by keunes** [akhilrex/podgrab#58]
Just after seeing https://github.com/AntennaPod/AntennaPod/issues/4960 and having read the readme, but without having tried or tested anything, I just felt like chipping in and be a podcastindex.org evengalist. It's a free and open source database with podcasts - integration with it would be a nice alternative to iTunes search.

**Comment by akhilrex** [comment]
This has been done. Thanks for the recommendation.

Just pull the latest image and rebuild the container once this build is complete - https://github.com/akhilrex/podgrab/runs/1966183445
