### ISSUE TITLE
[Feature request] Download queue

### ISSUE THREAD

**Issue by calvano915** [akhilrex/podgrab#62]
Feature request for a visualized tab to view pending download queue. Bonus if we can pause/cancel/change order. Bonus if we can change setting for simultaneous downloads, set speed, etc.

Thanks for all your effort in developing this!

**Comment by Drudoo** [comment]
Second this. I have 300+ in queue but it is hard to see the status and/or rearrange them.

**Comment by muppie** [comment]
Third this :)

**Comment by DoctorX17** [comment]
+++++ queue and at LEAST being able to cancel... I told it to download all episodes of a certain podcast, then realized it was nearly 2000 episodes, and I didn't ACTUALLY want to do that... so... Yeah XD Would be nice to be able to undo my mistake

Ideally, I'd like to see the following in a Downloads page:
- Number of episodes downloaded/downloading
- Current used space and estimated total after downloads complete
- Pause/cancel options -- individual downloads, or whole podcast, or all
- Priority control [weights for what series should be done first]
- Max daily download amount [just in case people have caps to worry about]

**Comment by akhilrex** [comment]
I'll be honest. There is no "download queue" as such. The numbers are simply the number of items in the DB which have "to be downloaded" status. They are then processed in FIFO order in the background. To build all these features would require to build the download pipeline as a full fledged module. 

Although I will try to build these whenever I can, I feel that the aim of the tool is to run in a fire and forget mode. Unless the tool fails to download a large number of files or is taking a lot of days to do that it should be able to process 300/2000/5000 downloads easily. For most users all these added abilities will be added complexity which might clutter the UX. Please share your thought.

@Drudoo Is the download stuck or have the 300 downloads completed?
@DoctorX17 Same question about your 2000 episodes. 

2000 episodes, ideally should not take a long time. It that is happening then it could be an issue in the core logic which I will fix.

**Comment by DoctorX17** [comment]
My 2000 episodes downloaded without issue, but it took several hours -- it was about 153GB in total, and I don't have the fastest internet connection. It worked out for me, but I can imagine someone with limited disk space or a datacap having a big problem if they made that same mistake.

**Comment by akhilrex** [comment]
This has been resolved some time back with better queue management. Please reopen if you still face this issue.
