### ISSUE TITLE
Miscellaneous Feature Requests

### ISSUE THREAD

**Issue by DoctorX17** [akhilrex/podgrab#63]
Loving this for archiving my favorite podcasts! Simple setup, working smoothly. There's a few things that I think would be nice to have though...

Player:
- Not sure how the Player is currently getting a queue, but it would be nice to be able to create the queue by adding individual episodes or podcasts, arrange/remove items from the queue, etc. [Playlists?]
- Better speed control
     - Faster speeds? I actually listen to a lot of podcasts at 3x in my favorite app, so that would be nice
     - plus and minus for speed, rather than cycling thru, or click on the speed to get a list of options
     - speed granularity -- maybe 0.1 or 0.2 intervals?

General podcast listing: 
- Size control in list format would be nice
- Ordering by number of episodes
- Hide/show played podcasts

Podcast pages:
- Change order -- newest to oldest or oldest to newest
- Select number of podcasts shown per page
- More page navigation:
     - "Older" and "Newer" can be very tedious for a podcast with hundreds of episodes, when each button only goes 10 episodes at a time -- maybe options of "Oldest", page numbers, and "Newest"?
- Hide/show played episodes

More a wish list than anything -- thanks for all your hard work so far!

**Comment by akhilrex** [comment]
Rebuild your container with the latest image and you will get the following
1. Added 2x and 3x speed options. Granularity or +- will be UX overload for most users and might result in a low impact/high effort scenario. Not picking that up for now.
2. Sorting by episode count enabled.
3. Improved Pagination - both oldest and newest as well as ability to jump to a specific page.

The app already has the ability to enqueue episodes/full podcasts to the current player playlist. If there is an existing player window, there will be a + button in the podcasts and episodes list page items. Clicking that will all that item to the current queue. In case the + button is not coming on your deployment, please ensure you have allowed for websockets.

I don't understand "size control" in the list. Please elaborate.

The episodes page is already in pipeline for a full overhaul. Should be able to close those soon.

**Comment by DoctorX17** [comment]
Silly question, as I'm new to Docker... How do I rebuild? I'm using unRAID, and the update feature gives an error "Configuration not found. Was this container created using this plugin?" -- I had originally created it using the CLI and the command to build the container with local volumes.

Size control -- currently, when viewing the podcast list, 3 or 4 podcasts takes up the whole page with the podcast's album art and titles, as well as space between lines -- so it would be nice to be able to fit more on the screen. I guess scaling would be a better word

**Comment by akhilrex** [comment]
I don't really have any experience with unRAID so I won't be able to help you with that. I recommend you check out some unRAID specific forum for that. If you used the CLI to build it then that would be the best way to go forward. If you used docker-compose then you can do a 

```
docker-compose pull
docker-compose restart
```

I think I understand the list point. Let me see what can be done.

**Comment by DoctorX17** [comment]
Figured it out, had to remove and re-add it with 'stop' and 'rm' commands, then run.

Thanks again for your work -- looking good!

**Comment by akhilrex** [comment]
All the points mentioned in the original issue have been addressed and released. Please rebuild the container with the latest image and check it out.
