### ISSUE TITLE
Ability to Change Download Location

### ISSUE THREAD

**Issue by dannyhanes** [akhilrex/podgrab#69]
It looks like downloads are being stored in the same folder as the .db file. Ideally I would like to set an environmental variable or have a setting to store them somewhere else. I have an attached NAS that I would like to point the downloads to.

**Comment by undaunt** [comment]
The database and backups are stored in /config but the podcasts are stored in /assets. I'm doing the following with compose:

```
      - $DOCKERDIR/podgrab:/config
      - $MEDIADIR/podcasts:/assets
```

Are you seeing everything in one folder? What are your volume mappings?

**Comment by dannyhanes** [comment]
So I used the Ubuntu installation instructions, not docker.

**Comment by akhilrex** [comment]
Hi

Please check if the .env file has been properly copied at the install location. If the file does not exist either copy the one from the git repo or create a new one with following content

``` env
CONFIG=.
DATA=./assets
CHECK_FREQUENCY = 10
PASSWORD=
```

Restart the service once done. You might have to delete and readd the podcasts.

**Comment by dannyhanes** [comment]
@akhilrex Ah ok, I found the issue. The .env didn't get copied over. 

Following the instructions for the ubuntu install, you need to add the following command to move the hidden .env file
`mv -v dist/.* /usr/local/bin/podgrab/`

I'll add the path now and see how it goes. 
Thanks!

**Comment by akhilrex** [comment]
Seems to be resolved
