### ISSUE TITLE
Patreon RSS Feeds Do Not Pull Correct Date

### ISSUE THREAD

**Issue by Cairxoxo** [akhilrex/podgrab#7]
Hi there,

As the title says, I've added a few Patreon RSS feeds, and PodGrab does not grab the correct date. See image:

![Capture](https://user-images.githubusercontent.com/40452204/98495403-2880d200-2293-11eb-8d17-c4e34df3433d.PNG)

![Capture](https://user-images.githubusercontent.com/40452204/98495458-46e6cd80-2293-11eb-924f-6eba82245dec.PNG)

**Comment by akhilrex** [comment]
I have fixed this issue. I recommend that you rebuild the container with
the latest image and delete and readd the podcast.

Please share the podcast RSS link if the issue persists.

Thanks and Regards

Akhil Gupta

**Comment by Cairxoxo** [comment]
Hey Akhil - thanks, nuked the container and config folder and repulled the image and it's working now.
