### ISSUE TITLE
Panic Recovered - template: episodes.html

### ISSUE THREAD

**Issue by undaunt** [akhilrex/podgrab#71]
I'm seeing an odd log error whenever I load an episode page of various podcasts. I'm not sure what to make of it, or if it is a problem, but as it said 'panic recovered' I figure it may be important.

![podgrab error](https://user-images.githubusercontent.com/31376520/112225512-28ea8b80-8bea-11eb-8731-7f211320f051.PNG)

**Comment by akhilrex** [comment]
Thanks for pointing this out. I have pushed a fix for this. Please rebuild this once image in created
