### ISSUE TITLE
self-hosted no podcast image on main page

### ISSUE THREAD

**Issue by Code-Slave** [akhilrex/podgrab#74]
the self-hosted podcast has the blank default image on home page. the episodes are fine its just the main page

**Comment by akhilrex** [comment]
Can you please share the URL of the podcast?

Thanks and Regards

Akhil Gupta

**Comment by akhilrex** [comment]
Seems to be working fine

![image](https://user-images.githubusercontent.com/576190/112558345-8d793680-8df4-11eb-9adf-38e43488162a.png)

I added this using the search functionality.

**Comment by Code-Slave** [comment]
I did the same and get the default image. just itunes search

**Comment by akhilrex** [comment]
I deleted the podcast and re-added it and it is still showing the correct image. Please try re-adding it once.

**Comment by Code-Slave** [comment]
that worked it seems
