### ISSUE TITLE
Player progress bar showing incorrect times and playback position

### ISSUE THREAD

**Issue by coopermf** [akhilrex/podgrab#75]
For all podcasts I add, the total length of the episode displayed at the ending of the player progress bar is incorrect and the player will not accurately display the time for current playback position.

**Comment by akhilrex** [comment]
Can you please share a screenshot and any podcast for which it is happening?

**Comment by coopermf** [comment]
The podcast player displays the episode length as 29:25 as opposed to the actual length 1:29:25

The progress bar will track accurately up to one hour then once it hits one hour it will start from 0.

the podcast rss feed used here is: https://2bears1cave.libsyn.com/rss
![podgrab-player](https://user-images.githubusercontent.com/17753396/112681925-9554cd00-8e2c-11eb-9e73-8fbeef09ebbb.png)

**Comment by smasterfree** [comment]
![image](https://user-images.githubusercontent.com/2479407/112740620-ed1c4100-8fb0-11eb-8f96-3627fd597485.png)
Same  problem. The total length is incorrect.

Will you consider use this podcast library https://github.com/jessuni/shikwasa, it has more features such as forward 10s and chapters. Thank you.

**Comment by akhilrex** [comment]
Hi

This has been done. Please rebuild the container and check.
