### ISSUE TITLE
Wrong media URL when using non default path for data directory

### ISSUE THREAD

**Issue by blacksponge** [akhilrex/podgrab#78]
Hello,

I am running podgrab without docker and wanted it to download media to `/data/media/podcasts` but doing so breaks the media url which seems to be formed by the full path to the file prepend by a slash. This result in the client querying `<hostname>/data/media/podcasts/...` instead of `/assets`. It seems that any data directory not named `assets` will fail in the same way.

I think that only storing the relative path from the data directory and compute the full path when needed would be better. I don't mind trying to fix it if you okay with that design.

Regards,

Gaël

**Comment by akhilrex** [comment]
Hi 

The ubuntu installation process is very new so such issues might come up. I think I understand whats happening. I will try to close this soon.

**Comment by akhilrex** [comment]
Can you please update the installation with the latest code and try again.

**Comment by blacksponge** [comment]
Thank you for the quick response. The download button on the episodes page is now correctly working but the player is not.

I have set the `DATA` variable to `DATA=podcast-data` (but anything other than `assets` would do) in `.env` then tried to play a episode, the url request is `http://localhost:8080/podcast-data/Camille/Camille-repond-a-vos-questions.mp3` which of course got a 404 reply. This is I think due to the player using the absolute `DownloadPath` and not the `/podcastitems/:id/file` route.

**Comment by akhilrex** [comment]
I'll fix that as well.

Thanks and Regards

Akhil Gupta

**Comment by akhilrex** [comment]
This has been fixed. Update the deployment and try again.

Thanks and Regards

Akhil Gupta
