### ISSUE TITLE
Failing tests for `internal/sanitize`

### ISSUE THREAD

**Issue by Ambroisie** [akhilrex/podgrab#80]
Hello.

I'm trying to package your program for [NixOS](https://github.com/NixOS/nixpkgs/issues/117284), however it seems that the tests for `internal/sanitize` are failing on `master`.

I can reproduce the error on Arch Linux too.

[Here's the log](https://pastebin.com/jHAzQHkt).

On a related note, do you plan to start tagging your releases at some point? (probably should be discussed in another issue though)

**Comment by akhilrex** [comment]
I will look into it.

Thanks and Regards

Akhil Gupta

**Comment by akhilrex** [comment]
This has been fixed. The tests should not fail now.
