### ISSUE TITLE
[Bug] album art missing while offline

### ISSUE THREAD

**Issue by muse-sisay** [akhilrex/podgrab#81]
Podgrab fetch's album art every time the page loads and doesn't save them locally. So if you are offline ( which I was for 2 weeks) it wont display the album art for podcasts.

**Comment by akhilrex** [comment]
Are you talking about podcast image or episode image?

Thanks and Regards

Akhil Gupta

**Comment by muse-sisay** [comment]
Thank you for a quick reply.

Both podcast and episode images don't show up.

**Comment by akhilrex** [comment]
Just to confirm : you have enabled image download in settings?

Note: podcast images are anyways not being cached so let's neglect those
for a while.

What kind of installation do you have? Docker or native?

Thanks and Regards

Akhil Gupta

**Comment by muse-sisay** [comment]
Yes, I have enabled image download in settings.  using your docker yaml file.

I have docker installation.  using your docker yaml file.

Some shows like "Darknet Diaries" have different image for each episode, which is different from the one embedded in the audio file.

**Comment by akhilrex** [comment]
This should be fixed now. Rebuild the container and try in an incognito window (in case of cacheing)

**Comment by muse-sisay** [comment]
> This should be fixed now. Rebuild the container and try in an incognito window (in case of cacheing)

I stoped the container, deleted the image, then pulled the new image from docker hub. Still Podgrab loads the images from the internet. Inside network tab could see the request is being forward to the internet (Podgrab returns status code301 ). I checked both on Firefox and Safari. Please see the attached screenshot

<img width="1683" alt="Screen Shot 2021-04-15 at 9 16 09 PM" src="https://user-images.githubusercontent.com/48902323/114919099-844a1b00-9e30-11eb-981d-bd8d08fd4320.png">

* I am using the latest image.

**Comment by akhilrex** [comment]
Please check the darknet diaries folder in assets and verify if downloaded
images do exist there.

The images are only downloaded for downloaded episodes.

Try incognito as well.

Thanks and Regards

Akhil Gupta

**Comment by akhilrex** [comment]
The 301s are most likely cached at your end. Please refer my screenshot. Same Podcast. The image for the one downloaded episode (Victor) is being sent by podgrab while the others are redirecting to the source.

Try this in some other browser or incognito mode.

![darknet](https://user-images.githubusercontent.com/576190/115101968-c628ad80-9f65-11eb-95d8-327eebbfa56f.jpg)

**Comment by muse-sisay** [comment]
It seems a hit and miss issue. Some podcasts have the `images` folder while others don't. One episode of Darknet Diaries does have album art and works perfectly. But  the majority of podcast shows don't have the images folder, so when the browser tries to load the album art it is redirected to the file hoster, even though the podcast file is present on disk.

Would it be possible for Podgrab to cache those 301 requests? That sounds more logical to me instead of the client fetching the images every time the page loads(if not cached).A scenario would be; client loads the page, if image file for the podcast/episode isn't present on disk, Podgrab would grab the image, save to disk then present it to client. (+1) Better yet, Podgrab would save images for all episode when it first loads podcast metadata. This removes the ambiguity of wether to redirect the request or not.

I know it an open issue(don't want to nag here too) It but would be nice to have version number on the settings page. I don't know if I am running the lates version or not other than comparing the hash value of the docker image I have against the one on docker hub. I am currently running `a1629504ec0e` .

Apologies for the late reply.

Thanks and Regards
Muse

**Comment by akhilrex** [comment]
Sorry for the delayed response (dad got COVID).

I have made the following changes which should help you with the issues

1. Changed 301s to 302s so that the browsers do not cache them as permanent redirects. This should ensure local images start getting used whenever they are downloaded.
2. Versioning has been added. Following the calver system. Current version can be found on the settings page.

**Comment by muse-sisay** [comment]
Sorry to hear about your dad. I hope he makes a swift recovery.  Stay safe.

Thank you for the effort. I will pull the latest image, later, to check it out.

PS. 
@akhilrex 
Can we have a discord server? Issue like #100 is something I feel like community member can help troubleshoot. It will also be a nice place to discuss the future and development of the project.
