### ISSUE TITLE
[Bug] Podcast episode will not play on Safari (macOS and iOS)

### ISSUE THREAD

**Issue by voreisthescore** [akhilrex/podgrab#83]
Similar issue as #51, podcasts not playing in Safari on both iOS and MacOS. Issue is persistent across multiple browsers on iOS due to Apples WebKit view, however it fails silently.
Issue is present on MacOS Safari and fails with:
```
[Error] Unhandled Promise Rejection: NotSupportedError: The operation is not supported.
	(anonymous function)
	rejectPromise
	play
	e (amplitude.min.js:1:2068)
	t (amplitude.min.js:1:60295)
	e (amplitude.min.js:1:60143)
```
Podcasts play fine on other browsers on macOS (Firefox, Chrome).
After some brief research many seem to indicate a file format issue yet after verification all files are mp3.
Unlike #51 rebuilding the container did not work.

**Comment by akhilrex** [comment]
AHH...

I must have inadvertently used some new js feature. This is quite vexing.

Will look into it.

Thanks and Regards

Akhil Gupta

**Comment by voreisthescore** [comment]
Any luck on this issue? If you point me in the right direction I can try take a look :)

**Comment by akhilrex** [comment]
I am sorry I have been a little tied up with work. I'll try to close this
soon.

Thanks and Regards

Akhil Gupta

**Comment by akhilrex** [comment]
This is fixed. Please rebuild container after latest image is built.

Thanks @strlght
