### ISSUE TITLE
Title Sorting Incorrect

### ISSUE THREAD

**Issue by Protektor-Desura** [akhilrex/podgrab#84]
When you have it sort by title of the podcast it isn't ignoring "The" and "A" in order to properly sort the titles of Podcasts so all the podcasts with "The" at the beginning of the title are being grouped together. It should ignore "A" and "The" for the purposes of putting the podcasts in alphabetical order.

**Comment by akhilrex** [comment]
Should be doable. Can you think of any more such words/phrases that need to
be skipped?

Thanks and Regards

Akhil Gupta

**Comment by Protektor-Desura** [comment]
You also want to make sure that titles like "A.I." are grouped as "A I" not skipping the A and putting it in the I's. "An" is going to be the same issue, it should be skipped.
