### ISSUE TITLE
Separate download path from asset path

### ISSUE THREAD

**Issue by Ambroisie** [akhilrex/podgrab#86]
If I understand correctly, the `DATA` environment variable is used both for storing the assets needed by the web interface, and to store the downloaded podcasts.

However I would like to be able to separate the assets from `podgrab` and my podcasts.

Did I misunderstand something about the configuration, or is there just no way to do that at the moment?

**Comment by akhilrex** [comment]
Podgrab web assets are stored in the webassets folder which is different
from the assets folder.

Only podcasts and their cover images are stored in assets.

Thanks and Regards

Akhil Gupta
