### ISSUE TITLE
Port Mapping behind traefik

### ISSUE THREAD

**Issue by dashentu** [akhilrex/podgrab#87]
**Please complete the following information**
 - Installation Type: Docker
 - Have you tried using the latest docker image / code base: yes
 - Great project! 

**Describe the bug**
Changing the port from 8080 to another one on docker-compose is not being picked up. This leads to port conflicts with default listening ports for traefik. I assume this is also the case with other reverse proxies (I have not tested them).  
From [issue 85](https://github.com/akhilrex/podgrab/issues/85), the info on readme does not say much on how to solve this, specially for non-GO crowd.

**Comment by akhilrex** [comment]
I have already updated this info in the Environment Variables table [here](https://github.com/akhilrex/podgrab#environment-variables)

Try setting the PORT environment variable to the port value you want and let me know if it works.

**Comment by dashentu** [comment]
It worked all fine after changing the port variable. 
However, the moment I put it behind traefik, it defaults back to 8080. I think this is on traefik, not podgrab. I will probe further on traefik.
