### ISSUE TITLE
[Feature Request] Filter by Dates (PubDate, Downloaded, Added)

### ISSUE THREAD

**Issue by degan6** [akhilrex/podgrab#88]
Hello, 

First this is an awesome program and I love how easy you made it to use with docker.

I'm hoping you could add more filters so I can see episodes that were released only today or past x days.

Why?

The way I'm going to use it is by query the JSON paths eg:
`http://192.168.4.19:8085/podcastitems?page=1&count=100&isDownloaded=true&sorting=release_desc`

For episodes that were released only or downloaded today only. This will help me ensure the program is still downloading episodes. 

Thanks again for all your hard work on this.

**Comment by akhilrex** [comment]
If the purpose is to monitor the operational only then I feel that this can be achieved with the same API. Honestly, I feel that raising an alert if no new episodes are released/downloaded in a single day would raise a lot of false alarms. The threshold should be 3days min (my opinion)

If you can write basic json querying, you should be able to find out easily if any new episodes have been downloaded/released in the past 3 days using the same API you mentioned above.

Having said this, I will try to build the "last x days" feature whenever I can.

**Comment by akhilrex** [comment]
Were you able to figure it out or do you still need help?
