### ISSUE TITLE
[Feature Request] Add a string identifying the version number somewhere

### ISSUE THREAD

**Issue by czeigler** [akhilrex/podgrab#89]
I think it would be helpful to have a version number somewhere in the UI so that I know if I'm on the latest version.  This would be especially helpful while the application is in active development.  Maybe it could go on the settings page?  Or an inconspicuous message in a footer?

**Comment by akhilrex** [comment]
I have been meaning to do this for quite some time. Ideally I would want to
make it a part of the build system as well as tag the docker images
accordingly as well. I will definitely look into this.

Thanks and Regards

Akhil Gupta

**Comment by akhilrex** [comment]
This has been done. Following the calver versioning system. Version number can be found on the settings page of the app and the top of Readme.
