### ISSUE TITLE
podgrab icon

### ISSUE THREAD

**Issue by after99** [akhilrex/podgrab#96]
have u [icon for homer](https://github.com/NX211/homer-icons)?

**Comment by akhilrex** [comment]
I'll be honest. I don't really even have an icon :).

I'll get it on homer and Heimdall whener I have one.

Thanks and Regards

Akhil Gupta

**Comment by muse-sisay** [comment]
@after99 Did you find an icon to use on homer?

**Comment by akhilrex** [comment]
I am sorry but not yet.

Thanks and Regards

Akhil Gupta

**Comment by shurushetr** [comment]
guys, just draw one and offer it to the author.

**Comment by avenom** [comment]
Simple circle icon.

![podgrab](https://github.com/akhilrex/podgrab/assets/17644125/91a09665-8585-4b9a-ae7f-8edd3ac704bd)
