### ISSUE TITLE
[Feature request] Adding existing podcasts

### ISSUE THREAD

**Issue by volcs0** [akhilrex/podgrab#97]
I have a large library of podcasts downloaded as MP3s. I'd like to see my podgrab library with these podcasts. In many instances, these episodes are no longer available for download, so it is not just a matter of re-downloading them. Thanks.

**Comment by akhilrex** [comment]
If the existing podcast episodes follow the podgrab naming convention then
you can just copy them to the assets path and then add the podcast. The app
will not download the same file again and use the existing file.

Please try this and let me know.

Thanks and Regards

Akhil Gupta

**Comment by akhilrex** [comment]
Did you try this?

**Comment by ev-w** [comment]
I can't answer for @volcs0 but I tried doing this last night and it worked, although it seems you'd need to add the podcast with the setting to download all episodes, as I had to manually go through and click the download to server button for the files to be recognized.

**Comment by akhilrex** [comment]
You can use the download all files button on the home page for that.

Thanks and Regards

Akhil Gupta
