### ISSUE TITLE
[Feature request] Support for chapter markers

### ISSUE THREAD

**Issue by muse-sisay** [akhilrex/podgrab#98]
Some shows like [Self-Hosted](https://selfhosted.show/) contain timestamp information in the metadata. Would be great to have the ability to jump around the podcast using the timestamps.

**Comment by akhilrex** [comment]
Can you point me to a specific episode in this podcast so that I can check whether this information is being provided in the RSS data or not?

**Comment by muse-sisay** [comment]
Hey Akhil, all their episodes contain chapter markers. The chapter markers are embedded inside the metadata of the `.mp3` file. They can be viewed by running `ffprobe` on the file.

```bash
$  ffprobe 21-2020-06-04-20-One-is-None.mp3
...
Input #0, mp3, from '21-2020-06-04-20-One-is-None.mp3':
  Metadata:
    encoder         : LAME 64bits version 3.100 (http://lame.sf.net)
    track           : 20
    TLEN            : 2166009
    comment         : You're not a true self-hoster until you've lost your entire configuration at least once. Alex does a deep dive into cloud backup, plus we need your help to find the right Wifi solution for a listener.
    album           : Self-Hosted
    genre           : Podcast
    copyright       : 2020 Jupiter Broadcasting
    encoded_by      : Jupiter Broadcasting
    TGID            : http://selfhosted.show/20
    title           : Self-Hosted 20: One is None
    publisher       : Jupiter Broadcasting
    artist          : Jupiter Broadcasting
    TOPE            : Jupiter Broadcasting
    date            : 2020
  Duration: 00:36:06.05, start: 0.025056, bitrate: 97 kb/s
    Chapter #0:0: start 0.000000, end 54.000000
    Metadata:
      title           : Intro
    Chapter #0:1: start 54.000000, end 656.000000
    Metadata:
      title           : Chris' BTRFS Data Disaster
    Chapter #0:2: start 656.000000, end 1308.000000
    Metadata:
      title           : Cloud Backup Strategies
    Chapter #0:3: start 1308.000000, end 1465.000000
    Metadata:
      title           : Home Assistant Follow-Up
    Chapter #0:4: start 1465.000000, end 1782.000000
    Metadata:
      title           : Self-Hosted Wiki Follow-Up
    Chapter #0:5: start 1782.000000, end 2106.000000
    Metadata:
      title           : #askssh
    Chapter #0:6: start 2106.000000, end 2166.000000
    Metadata:
      title           : Outro
    Stream #0:0: Audio: mp3, 44100 Hz, mono, fltp, 96 kb/s
    Metadata:
      encoder         : LAME3.100
    Side data:
      replaygain: track gain - -3.300000, track peak - unknown, album gain - unknown, album peak - unknown,
    Stream #0:1: Video: mjpeg, yuvj444p(pc, bt470bg/unknown/unknown), 3000x3000 [SAR 28:28 DAR 1:1], 90k tbr, 90k tbn, 90k tbc
    Metadata:
      title           : image
      comment         : Other
```


There is no information regarding chapter markers in the RSS feed.

### LINKS
- **[RSS feed](https://feeds.fireside.fm/selfhosted/rss)** 
- **[MP3 File](https://media.fireside.fm/file/fireside-audio/podcasts/audio/7/7296e34a-2697-479a-adfb-ad32329dd0b0/episodes/4/407501f4-7d4c-4318-a31f-93e141596495/407501f4-7d4c-4318-a31f-93e141596495.mp3
)**

**Comment by akhilrex** [comment]
Hi 

Podgrab is primarily focused on downloading and archiving podcasts. A basic player has been added so that the tool becomes complete but in no way the intention of the tool was ever to become a full fledged player.

If the chapter info was coming in the XML, I would have definitely added it to the database but in this case it seems more like a feature for a player. I recommend that you use Podgrab to download and archive podcasts and use an advanced player to play the downloaded files.

**Comment by muse-sisay** [comment]
Greetings @akhilrex,

Hope you are doing great.

The chapter information is include in the XML(RSS feed). `podcast:chapters` tag includes a link to json file containing the chapter markers. [This](https://feeds.fireside.fm/selfhosted/json/episodes/b238d92c-c700-4f06-8f72-c6801ab9ddc1/chapters) one is from Self hosted podcast.

Because this is a closed  issue shall I open a new one?
