### ISSUE TITLE
[Feature request] Display Additional information on Player page

### ISSUE THREAD

**Issue by muse-sisay** [akhilrex/podgrab#99]
Some of the features I want to see in the future version of `podgrab`:
1. **Episode summary below player.** Save time by not having to go between episode page and player page to read summary for the episode I am listening too.
2. **Hyperlink Show page.** If I am listening to a podcast and if I click on the podcast name it takes me to the podcast(show) view. I can further explore 
3. **Chapter( timestamps)**. Ability to jump to chapters.

Sorry, I know I am asking a lot from an open source project. But this project has changed the way I archive, organize and listen to podcasts. I am grateful for the time you spend on this project. So I have dedicated my free time to learning Golang to help you out with this project. Hopefully I will be of some help to you.

**Comment by akhilrex** [comment]
Hi

Can you please elaborate on point 2. I am not sure where the link can be placed?

**Comment by muse-sisay** [comment]
>
> Can you please elaborate on point 2. I am not sure where the link can be placed?

Podcast title on the player page.

**Comment by akhilrex** [comment]
I have added the episode summary on the Player page. Please rebuild your container with the latest image once the current build is complete.

**Comment by muse-sisay** [comment]
👍🏾 It looks amazing especially on mobile. Thank you for taking the time to implement this.

**Comment by akhilrex** [comment]
I looked into the chapters thing and that would not be possible in the current setup and the existing player. I recommend that you use the newly built RSS feature of Podgrab to play files in some better podcast player using podgrab as your backend.

**Comment by muse-sisay** [comment]
Reading back, the second point doesn't make a lot of sense. Let me elaborate a bit. When clicking on the show name it's like clicking on a channel's name on YouTube while you are watching. It takes you to the channels page in Podgrab's case to show page.
